import { Regulation, Chapter } from "./types";

export const mockRegulations: Regulation[] = [
  {
    id: "1",
    slug: "rgpd",
    title: "Règlement général sur la protection des données",
    official_name: "Règlement (UE) 2016/679 du Parlement européen et du Conseil",
    reference: "Règlement (UE) 2016/679",
    adoption_date: "2016-04-27",
    application_date: "2018-05-25",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32016R0679",
    status: "in_force",
    summary: "Le RGPD établit des règles relatives à la protection des personnes physiques à l'égard du traitement des données à caractère personnel et à la libre circulation de ces données. Il renforce les droits des individus et responsabilise les organisations qui traitent des données personnelles.",
    icon_emoji: "🔒",
    category: "Données",
  },
  {
    id: "2",
    slug: "dsa",
    title: "Règlement sur les services numériques (DSA)",
    official_name: "Règlement (UE) 2022/2065 relatif à un marché intérieur des services numériques",
    reference: "Règlement (UE) 2022/2065",
    adoption_date: "2022-10-19",
    application_date: "2024-02-17",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2065",
    status: "in_force",
    summary: "Le DSA modernise le cadre réglementaire applicable aux services intermédiaires en ligne. Il impose des obligations graduées selon la taille des plateformes, renforce la lutte contre les contenus illicites et améliore la transparence algorithmique.",
    icon_emoji: "🌐",
    category: "Plateformes",
  },
  {
    id: "3",
    slug: "dma",
    title: "Règlement sur les marchés numériques (DMA)",
    official_name: "Règlement (UE) 2022/1925 relatif aux marchés contestables et équitables dans le secteur numérique",
    reference: "Règlement (UE) 2022/1925",
    adoption_date: "2022-09-14",
    application_date: "2023-05-02",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R1925",
    status: "in_force",
    summary: "Le DMA vise à garantir des marchés numériques contestables et équitables. Il cible les \"contrôleurs d'accès\" (gatekeepers) — les grandes plateformes systémiques — et leur impose des obligations et interdictions spécifiques pour prévenir les pratiques anticoncurrentielles.",
    icon_emoji: "⚖️",
    category: "Concurrence",
  },
  {
    id: "4",
    slug: "ai-act",
    title: "Règlement sur l'intelligence artificielle (AI Act)",
    official_name: "Règlement (UE) 2024/1689 établissant des règles harmonisées concernant l'intelligence artificielle",
    reference: "Règlement (UE) 2024/1689",
    adoption_date: "2024-06-13",
    application_date: "2026-08-02",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    status: "partially_applicable",
    summary: "L'AI Act établit un cadre juridique harmonisé pour les systèmes d'IA dans l'UE, fondé sur une approche par niveaux de risque (inacceptable, élevé, limité, minimal). Il réglemente le développement, la mise sur le marché et l'utilisation des systèmes d'IA.",
    icon_emoji: "🤖",
    category: "Intelligence Artificielle",
  },
  {
    id: "5",
    slug: "dga",
    title: "Data Governance Act (DGA)",
    official_name: "Règlement (UE) 2022/868 portant sur la gouvernance européenne des données",
    reference: "Règlement (UE) 2022/868",
    adoption_date: "2022-05-30",
    application_date: "2023-09-24",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R0868",
    status: "in_force",
    summary: "Le DGA crée un cadre pour le partage volontaire des données en Europe. Il réglemente la réutilisation des données du secteur public, encadre les services d'intermédiation de données et reconnaît le concept d'altruisme des données.",
    icon_emoji: "📊",
    category: "Données",
  },
  {
    id: "6",
    slug: "nis2",
    title: "Directive NIS2",
    official_name: "Directive (UE) 2022/2555 concernant des mesures destinées à assurer un niveau élevé commun de cybersécurité",
    reference: "Directive (UE) 2022/2555",
    adoption_date: "2022-12-14",
    application_date: "2024-10-17",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022L2555",
    status: "in_force",
    summary: "NIS2 élargit considérablement le champ d'application de la directive NIS originale en matière de cybersécurité. Elle impose des exigences renforcées de gestion des risques et de notification des incidents à un large spectre d'entités essentielles et importantes.",
    icon_emoji: "🛡️",
    category: "Cybersécurité",
  },
  {
    id: "7",
    slug: "data-act",
    title: "Data Act",
    official_name: "Règlement (UE) 2023/2854 concernant des règles harmonisées portant sur l'équité de l'accès aux données",
    reference: "Règlement (UE) 2023/2854",
    adoption_date: "2023-11-13",
    application_date: "2025-09-12",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R2854",
    status: "partially_applicable",
    summary: "Le Data Act définit des règles sur l'accès aux données générées par des objets connectés et services associés. Il vise à libérer la valeur économique des données industrielles en garantissant un accès équitable pour les utilisateurs, les entreprises et le secteur public.",
    icon_emoji: "💾",
    category: "Données",
  },
  {
    id: "8",
    slug: "cra",
    title: "Cyber Resilience Act (CRA)",
    official_name: "Règlement (UE) 2024/2847 sur la cyber-résilience",
    reference: "Règlement (UE) 2024/2847",
    adoption_date: "2024-10-23",
    application_date: "2027-12-11",
    eurlex_url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R2847",
    status: "partially_applicable",
    summary: "Le CRA impose des exigences de cybersécurité obligatoires pour les produits comportant des éléments numériques (logiciels, IoT, etc.) tout au long de leur cycle de vie. Il introduit le marquage CE en matière de cybersécurité.",
    icon_emoji: "🔐",
    category: "Cybersécurité",
  },
];

export const mockChapters: Record<string, Chapter[]> = {
  rgpd: [
    {
      id: "c1",
      regulation_id: "1",
      chapter_number: 1,
      title: "Dispositions générales",
      summary: "Définit l'objet, le champ d'application matériel et territorial du RGPD. Pose les définitions fondamentales : données personnelles, traitement, responsable du traitement, sous-traitant.",
      key_articles: ["Art. 1", "Art. 2", "Art. 3", "Art. 4"],
      sort_order: 1,
    },
    {
      id: "c2",
      regulation_id: "1",
      chapter_number: 2,
      title: "Principes",
      summary: "Établit les 7 principes fondamentaux du traitement des données : licéité, loyauté, transparence, limitation des finalités, minimisation, exactitude, limitation de la conservation, intégrité et confidentialité.",
      key_articles: ["Art. 5", "Art. 6", "Art. 7", "Art. 8", "Art. 9", "Art. 10"],
      sort_order: 2,
    },
    {
      id: "c3",
      regulation_id: "1",
      chapter_number: 3,
      title: "Droits de la personne concernée",
      summary: "Consacre les droits des individus : droit d'accès, de rectification, d'effacement (droit à l'oubli), de portabilité, d'opposition, et relatifs à la prise de décision automatisée.",
      key_articles: ["Art. 12", "Art. 13", "Art. 14", "Art. 15", "Art. 16", "Art. 17", "Art. 18", "Art. 20", "Art. 21", "Art. 22"],
      sort_order: 3,
    },
    {
      id: "c4",
      regulation_id: "1",
      chapter_number: 4,
      title: "Responsable du traitement et sous-traitant",
      summary: "Définit les obligations des responsables de traitement et sous-traitants : privacy by design, DPO, analyses d'impact (AIPD), notification des violations de données.",
      key_articles: ["Art. 24", "Art. 25", "Art. 28", "Art. 32", "Art. 33", "Art. 34", "Art. 35", "Art. 37"],
      sort_order: 4,
    },
    {
      id: "c5",
      regulation_id: "1",
      chapter_number: 5,
      title: "Transferts vers des pays tiers",
      summary: "Encadre les transferts de données personnelles hors de l'UE/EEE : décisions d'adéquation, clauses contractuelles types (CCT), règles d'entreprise contraignantes (BCR).",
      key_articles: ["Art. 44", "Art. 45", "Art. 46", "Art. 47", "Art. 49"],
      sort_order: 5,
    },
    {
      id: "c6",
      regulation_id: "1",
      chapter_number: 6,
      title: "Autorités de contrôle",
      summary: "Organise le système de supervision : indépendance des autorités nationales (CNIL en France), mécanisme de guichet unique (one-stop-shop) pour les traitements transfrontaliers.",
      key_articles: ["Art. 51", "Art. 52", "Art. 55", "Art. 56", "Art. 57", "Art. 58"],
      sort_order: 6,
    },
    {
      id: "c7",
      regulation_id: "1",
      chapter_number: 7,
      title: "Coopération et cohérence",
      summary: "Mécanismes de coopération entre autorités nationales et Comité européen de la protection des données (CEPD/EDPB). Procédure de cohérence pour les questions d'application générale.",
      key_articles: ["Art. 60", "Art. 63", "Art. 64", "Art. 65", "Art. 68", "Art. 70"],
      sort_order: 7,
    },
    {
      id: "c8",
      regulation_id: "1",
      chapter_number: 8,
      title: "Voies de recours, responsabilité et sanctions",
      summary: "Prévoit les recours juridictionnels, la responsabilité civile et le régime de sanctions administratives pouvant atteindre 20 M€ ou 4% du chiffre d'affaires mondial annuel.",
      key_articles: ["Art. 77", "Art. 78", "Art. 79", "Art. 82", "Art. 83", "Art. 84"],
      sort_order: 8,
    },
  ],
  dsa: [
    {
      id: "d1",
      regulation_id: "2",
      chapter_number: 1,
      title: "Dispositions générales",
      summary: "Champ d'application du DSA : tous les services intermédiaires offerts aux destinataires établis ou situés dans l'UE, quelle que soit la localisation du prestataire.",
      key_articles: ["Art. 1", "Art. 2", "Art. 3"],
      sort_order: 1,
    },
    {
      id: "d2",
      regulation_id: "2",
      chapter_number: 2,
      title: "Responsabilité des prestataires",
      summary: "Maintient et précise les régimes d'exemption de responsabilité pour les activités de simple transport, de mise en cache et d'hébergement. Introduit l'obligation de réagir rapidement (notice and action).",
      key_articles: ["Art. 4", "Art. 5", "Art. 6", "Art. 7", "Art. 8", "Art. 9"],
      sort_order: 2,
    },
    {
      id: "d3",
      regulation_id: "2",
      chapter_number: 3,
      title: "Obligations de diligence",
      summary: "Obligations graduées selon la catégorie : prestataires intermédiaires (tous), hébergeurs, plateformes en ligne, très grandes plateformes (VLOP) et moteurs de recherche (VLOSE). Les VLOP ont les obligations les plus lourdes.",
      key_articles: ["Art. 11", "Art. 12", "Art. 14", "Art. 17", "Art. 24", "Art. 26", "Art. 27", "Art. 33", "Art. 34", "Art. 35"],
      sort_order: 3,
    },
    {
      id: "d4",
      regulation_id: "2",
      chapter_number: 4,
      title: "Mise en oeuvre et application",
      summary: "Coordinateurs des services numériques (CSN/DSC) dans chaque État membre. Rôle de la Commission européenne pour les VLOP/VLOSE. Mécanismes de coopération, audits et amendes.",
      key_articles: ["Art. 49", "Art. 50", "Art. 56", "Art. 65", "Art. 74"],
      sort_order: 4,
    },
  ],
  dma: [
    {
      id: "dm1",
      regulation_id: "3",
      chapter_number: 1,
      title: "Objet, champ d'application et définitions",
      summary: "Définit les services de plateforme essentiels (SPE) visés : services d'intermédiation, moteurs de recherche, réseaux sociaux, plateformes de partage de vidéos, messageries, systèmes d'exploitation, navigateurs, assistants virtuels, publicité en ligne, cloud.",
      key_articles: ["Art. 1", "Art. 2"],
      sort_order: 1,
    },
    {
      id: "dm2",
      regulation_id: "3",
      chapter_number: 2,
      title: "Contrôleurs d'accès (gatekeepers)",
      summary: "Critères de désignation des gatekeepers (seuils quantitatifs : 7,5 Md€ de CA, 45M d'utilisateurs actifs mensuels dans l'UE, 10 000 utilisateurs professionnels). Procédure de désignation par la Commission.",
      key_articles: ["Art. 3", "Art. 4", "Art. 5", "Art. 6", "Art. 7"],
      sort_order: 2,
    },
    {
      id: "dm3",
      regulation_id: "3",
      chapter_number: 3,
      title: "Pratiques interdites et obligations",
      summary: "Liste les obligations (do's) et interdictions (don'ts) applicables aux gatekeepers : interopérabilité, accès aux données, autodésignation équitable des apps, portabilité, etc.",
      key_articles: ["Art. 5", "Art. 6", "Art. 7"],
      sort_order: 3,
    },
    {
      id: "dm4",
      regulation_id: "3",
      chapter_number: 4,
      title: "Enquêtes et sanctions",
      summary: "Pouvoirs d'enquête de la Commission. Sanctions : jusqu'à 10% du CA mondial (20% en cas de récidive). Remèdes comportementaux et structurels en cas de violation systémique.",
      key_articles: ["Art. 16", "Art. 17", "Art. 18", "Art. 19", "Art. 26"],
      sort_order: 4,
    },
  ],
  "ai-act": [
    {
      id: "ai1",
      regulation_id: "4",
      chapter_number: 1,
      title: "Dispositions générales",
      summary: "Champ d'application, définitions clés (système d'IA, risque, opérateur, déployeur). Le règlement s'applique aux fournisseurs qui mettent sur le marché des systèmes d'IA et aux déployeurs établis ou situés dans l'UE.",
      key_articles: ["Art. 1", "Art. 2", "Art. 3"],
      sort_order: 1,
    },
    {
      id: "ai2",
      regulation_id: "4",
      chapter_number: 2,
      title: "Pratiques d'IA interdites",
      summary: "Interdit les systèmes d'IA présentant des risques inacceptables : manipulation subliminale, exploitation des vulnérabilités, notation sociale (social scoring), identification biométrique à distance en temps réel (sauf exceptions).",
      key_articles: ["Art. 5"],
      sort_order: 2,
    },
    {
      id: "ai3",
      regulation_id: "4",
      chapter_number: 3,
      title: "Systèmes d'IA à haut risque",
      summary: "Deux catégories : IA comme composant de produits soumis à la législation sectorielle (Annexe I), et IA dans des domaines sensibles (Annexe III) : infrastructure critique, éducation, emploi, services essentiels, justice, migration, démocratie.",
      key_articles: ["Art. 6", "Art. 7", "Art. 8", "Art. 9", "Art. 10", "Art. 13", "Art. 14", "Art. 15"],
      sort_order: 3,
    },
    {
      id: "ai4",
      regulation_id: "4",
      chapter_number: 4,
      title: "Modèles d'IA à usage général (GPAI)",
      summary: "Régime spécifique pour les modèles GPAI (ex: GPT-4, Gemini). Obligations de transparence et de copyright. Obligations renforcées pour les modèles GPAI présentant un risque systémique (>10^25 FLOPs d'entraînement).",
      key_articles: ["Art. 51", "Art. 52", "Art. 53", "Art. 54", "Art. 55"],
      sort_order: 4,
    },
    {
      id: "ai5",
      regulation_id: "4",
      chapter_number: 5,
      title: "Gouvernance et sanctions",
      summary: "Bureau IA (AI Office) au niveau européen. Autorités nationales compétentes. Sanctions : jusqu'à 35M€ ou 7% du CA mondial pour violation des interdictions, 15M€ ou 3% pour les autres violations.",
      key_articles: ["Art. 59", "Art. 64", "Art. 65", "Art. 99", "Art. 101"],
      sort_order: 5,
    },
  ],
  dga: [
    {
      id: "dg1",
      regulation_id: "5",
      chapter_number: 1,
      title: "Champ d'application et définitions",
      summary: "Définit les acteurs clés : détenteurs de données, utilisateurs de données, intermédiaires de données, organismes d'altruisme des données. Pose le cadre de la gouvernance des données européenne.",
      key_articles: ["Art. 1", "Art. 2"],
      sort_order: 1,
    },
    {
      id: "dg2",
      regulation_id: "5",
      chapter_number: 2,
      title: "Réutilisation des données du secteur public",
      summary: "Encadre la réutilisation des données protégées détenues par des organismes du secteur public (données personnelles, confidentielles, propriété intellectuelle de tiers). Conditions et garanties requises.",
      key_articles: ["Art. 3", "Art. 4", "Art. 5", "Art. 6", "Art. 7", "Art. 8"],
      sort_order: 2,
    },
    {
      id: "dg3",
      regulation_id: "5",
      chapter_number: 3,
      title: "Services d'intermédiation de données",
      summary: "Régime de notification obligatoire pour les prestataires de services d'intermédiation de données. Conditions d'exercice : neutralité, séparation des activités, non-commercialisation des données.",
      key_articles: ["Art. 10", "Art. 11", "Art. 12", "Art. 13", "Art. 14", "Art. 15"],
      sort_order: 3,
    },
    {
      id: "dg4",
      regulation_id: "5",
      chapter_number: 4,
      title: "Altruisme des données",
      summary: "Crée le statut d'organisation reconnue d'altruisme des données pour faciliter le partage volontaire de données à des fins d'intérêt général (recherche, statistiques, amélioration des services publics).",
      key_articles: ["Art. 16", "Art. 17", "Art. 18", "Art. 19", "Art. 20", "Art. 22"],
      sort_order: 4,
    },
  ],
};

export function getRegulationBySlug(slug: string): Regulation | undefined {
  return mockRegulations.find((r) => r.slug === slug);
}

export function getChaptersBySlug(slug: string): Chapter[] {
  return mockChapters[slug] || [];
}

export const mockStats = {
  regulations: 15,
  fiches: 11,
  concepts: 120,
};
