export interface RegulationData {
  id: string;
  badge: string;
  cat: string;
  name: string;
  ref: string;
  type: string;
  status: "active" | "partial" | "upcoming" | "transposed";
  statusLabel: string;
  title: string;
  fullName: string;
  nature: string;
  natureNote: string;
  context: string;
  summary: string;
  champ: string;
  actors: string[];
  obligations: string[];
  sanctions: { amount: string; detail: string }[];
  articulations: string;
  timeline: { date: string; event: string }[];
  link: string;
  updatedAt: string; // ISO date string, e.g. "2025-04-29"
  sanctionsIntro?: string; // Optional intro note displayed above sanctions list
}

export const regulationsData: RegulationData[] = [
  {
    id: "rgpd",
    badge: "RGPD",
    cat: "Données",
    name: "Protection des données",
    ref: "Règlement (UE) 2016/679",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "RGPD",
    fullName: "Règlement Général sur la Protection des Données",
    nature: "reglement",
    natureNote: "Le RGPD est un règlement européen : il est d'application directe dans tous les États membres de l'UE depuis le 25 mai 2018. Il ne nécessite pas de loi de transposition. Les États membres conservent néanmoins des marges de manœuvre sur certains points : l'âge du consentement des mineurs (entre 13 et 16 ans selon les pays, 15 ans en France), les traitements dans le cadre de l'emploi, les traitements à des fins journalistiques ou artistiques, et certaines dérogations pour le secteur public. En France, la loi Informatique et Libertés du 6 janvier 1978, modifiée en 2018, complète le RGPD sur ces aspects nationaux.",
    context: "Le RGPD remplace la directive 95/46/CE qui datait de 1995, une époque où internet en était à ses débuts, où les réseaux sociaux n'existaient pas et où le cloud computing n'avait pas de nom. En vingt ans, l'exploitation massive des données personnelles par les géants du numérique (profilage publicitaire, revente de données, surveillance) a rendu ce cadre obsolète. La directive posait un autre problème : en tant que directive, elle avait été transposée de manière hétérogène dans les États membres, créant un patchwork juridique nuisant à la fois aux entreprises (insécurité juridique) et aux citoyens (protections inégales). Le choix du règlement, d'application directe, vise précisément à unifier ce cadre. Le RGPD poursuit trois objectifs principaux :<ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li>renforcer les droits des personnes physiques sur leurs données ;</li><li>responsabiliser les organisations qui les traitent (principe d'accountability) ;</li><li>harmoniser la régulation à l'échelle de l'UE pour créer un marché unique de la donnée fondé sur la confiance.</li></ul>",
    summary: "Le RGPD encadre la collecte, le traitement et la circulation des données à caractère personnel des personnes situées dans l'Union européenne. Il constitue le texte socle de la protection des données en Europe et a une portée extraterritoriale : il s'applique à toute organisation dans le monde qui traite des données de personnes situées dans l'UE. Le règlement repose sur sept principes fondamentaux (licéité, limitation des finalités, minimisation, exactitude, limitation de conservation, intégrité/confidentialité, responsabilité) et six bases légales possibles pour traiter des données (consentement, contrat, obligation légale, intérêts vitaux, mission d'intérêt public, intérêt légitime). Il consacre des droits renforcés pour les personnes (accès, rectification, effacement, portabilité, opposition, limitation) et impose aux responsables de traitement des obligations structurantes : registre des traitements, analyses d'impact, notification des violations dans les 72 heures, privacy by design et by default, et désignation d'un DPO dans certains cas.",
    champ: "Sur le plan matériel, le RGPD couvre tout traitement de données à caractère personnel, automatisé ou non (y compris les fichiers papier), à l'exception des activités purement personnelles ou domestiques, de la politique étrangère et de sécurité commune de l'UE, et des traitements par les autorités à des fins de prévention et détection des infractions pénales (couverts par la directive « Police-Justice » 2016/680).<br><br>Sur le plan territorial (article 3), il s'applique aux organisations établies dans l'UE quel que soit le lieu du traitement, et aux organisations hors UE qui ciblent des personnes dans l'UE (offre de biens/services ou suivi du comportement).",
    actors: [
      "Responsables de traitement (toute entité déterminant les finalités et moyens du traitement)",
      "Sous-traitants (entités traitant des données pour le compte du responsable)",
      "Délégué à la protection des données (DPO)",
      "CNIL (autorité de contrôle française)",
      "Comité européen de la protection des données (CEPD/EDPB)",
      "Personnes concernées (toute personne physique dont les données sont traitées)",
    ],
    obligations: [
      "<strong>Registre des activités de traitement (art. 30)</strong> : obligatoire pour les organisations de plus de 250 salariés, ou en dessous si le traitement présente un risque, concerne des données sensibles ou est régulier.",
      "<strong>Analyse d'impact (AIPD/DPIA, art. 35)</strong> : obligatoire lorsque le traitement est susceptible d'engendrer un risque élevé pour les droits et libertés : profilage systématique, surveillance à grande échelle, données sensibles à grande échelle.",
      "<strong>Privacy by design et by default (art. 25)</strong> : la protection des données doit être intégrée dès la conception du système et par défaut (seules les données nécessaires sont collectées, durée de conservation minimale, accès restreint).",
      "<strong>Notification des violations (art. 33-34)</strong> : notification à l'autorité de contrôle dans les 72 heures suivant la découverte d'une violation. Information des personnes concernées si le risque est élevé.",
      "<strong>Désignation d'un DPO (art. 37-39)</strong> : obligatoire pour les autorités publiques, les organisations dont l'activité implique un suivi régulier et systématique à grande échelle, ou le traitement de données sensibles à grande échelle.",
      "<strong>Encadrement des transferts hors UE (chapitre V)</strong> : les transferts vers des pays tiers ne sont autorisés que sous conditions : décision d'adéquation, clauses contractuelles types (CCT), règles d'entreprise contraignantes (BCR).",
      "<strong>Droits des personnes (chapitre III)</strong> : le RGPD consacre les droits suivants :<ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li>Droit d'accès (art. 15)</li><li>Droit de rectification (art. 16)</li><li>Droit à l'effacement (art. 17)</li><li>Droit à la limitation du traitement (art. 18)</li><li>Droit à la portabilité des données (art. 20)</li><li>Droit d'opposition (art. 21)</li><li>Droit de ne pas faire l'objet d'une décision entièrement automatisée (art. 22)</li></ul>",
    ],
    sanctionsIntro: "L'article 83 du RGPD dispose que les amendes administratives imposées en cas de manquement doivent être effectives, proportionnées et dissuasives. Elles varient selon la gravité de la violation et sont déterminées au cas par cas par l'autorité de contrôle compétente.",
    sanctions: [
      { amount: "20 M€ ou 4 % du CA mondial", detail: "Pour violation des principes fondamentaux, des droits des personnes ou des règles de transfert (art. 83§5)" },
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour manquement aux obligations du responsable/sous-traitant : registre, DPO, notification, privacy by design (art. 83§4)" },
      { amount: "Sanctions pénales (France)", detail: "L'article 226-16 du Code pénal dispose que le fait de procéder ou de faire procéder à des traitements de données à caractère personnel sans respecter les formalités préalables prévues par la loi est puni de cinq ans d'emprisonnement et de 300 000 € d'amende. Ces sanctions s'appliquent également en cas de collecte frauduleuse, de détournement de finalité et d'entrave aux contrôles de la CNIL." },
      { amount: "Bilan 2025 : sanctions prononcées par la CNIL", detail: "Près de 487 millions d'euros d'amendes sur 259 décisions au total, dont 83 sanctions, 143 mises en demeure, 31 rappels aux obligations légales et 2 avertissements. Principales amendes : Google 325 M€, Shein 150 M€, Free 42 M€, France Travail 5 M€." },
    ],
    articulations: "Le RGPD est le texte socle : presque tous les autres textes de droit du numérique européen interagissent avec lui. La directive ePrivacy est sa lex specialis pour les communications électroniques (cookies). Le DSA s'articule avec le RGPD pour la modération de contenu et la publicité ciblée. L'AI Act renvoie au RGPD pour le traitement des données d'entraînement. Le Data Act et le DGA organisent le partage des données tout en renvoyant au RGPD dès que des données personnelles sont concernées.",
    timeline: [
      { date: "27 avril 2016", event: "Adoption du règlement par le Parlement européen et le Conseil" },
      { date: "25 mai 2018", event: "Entrée en application dans tous les États membres" },
      { date: "Juil. 2020", event: "Arrêt Schrems II (CJUE) : invalidation du Privacy Shield UE–États-Unis" },
      { date: "Juil. 2023", event: "Adoption du Data Privacy Framework UE–États-Unis" },
      { date: "2025", event: "Près de 487 M€ d'amendes prononcées par la CNIL sur 259 décisions, un montant record" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32016R0679",
    updatedAt: "2025-04-29",
  },
  {
    id: "dga",
    badge: "DGA",
    cat: "Données",
    name: "Gouvernance des données",
    ref: "Règlement (UE) 2022/868",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DGA",
    fullName: "Data Governance Act — Règlement sur la gouvernance européenne des données",
    nature: "reglement",
    natureNote: "Le DGA est un règlement européen d'application directe dans tous les États membres depuis le 24 septembre 2023. Aucune transposition nationale n'est nécessaire. Les États membres doivent cependant désigner les organismes compétents pour la mise en œuvre.",
    context: "L'Union européenne a constaté que d'immenses volumes de données détenues par le secteur public ou générées par les citoyens et entreprises restaient sous-exploités, faute de mécanismes de confiance permettant leur partage. Le DGA s'inscrit dans la stratégie européenne des données de 2020, aux côtés du Data Act. Son objectif est de créer les conditions de confiance nécessaires au partage volontaire de données entre organisations, sans remettre en cause la protection des données personnelles (RGPD).",
    summary: "Le Data Governance Act établit un cadre de gouvernance pour faciliter le partage et la réutilisation des données au sein de l'UE. Il encadre les conditions de réutilisation des données protégées du secteur public, crée un régime de notification pour les services d'intermédiation de données (data marketplaces), et établit un cadre pour l'altruisme en matière de données permettant aux citoyens et entreprises de mettre volontairement leurs données à disposition pour des objectifs d'intérêt général.",
    champ: "Organismes du secteur public détenant des données protégées, fournisseurs de services d'intermédiation de données, organisations d'altruisme en matière de données, et utilisateurs de ces services dans l'ensemble de l'UE.",
    actors: [
      "Organismes du secteur public détenant des données protégées",
      "Services d'intermédiation de données (data marketplaces, data trusts)",
      "Organisations d'altruisme en matière de données",
      "Comité européen de l'innovation dans le domaine des données (EDIB)",
      "Autorités compétentes nationales désignées par chaque État membre",
    ],
    obligations: [
      "<strong>Réutilisation des données du secteur public (chapitre II)</strong> — les organismes publics qui autorisent la réutilisation de données protégées doivent le faire dans des conditions non discriminatoires, transparentes et proportionnées. Les exclusivités de réutilisation sont limitées à 12 mois.",
      "<strong>Services d'intermédiation de données (chapitre III)</strong> — les prestataires doivent notifier leur activité à l'autorité compétente, rester neutres, et garantir la sécurité et l'interopérabilité.",
      "<strong>Altruisme en matière de données (chapitre IV)</strong> — les organisations collectant des données à des fins d'intérêt général peuvent s'enregistrer comme « organisations d'altruisme en matière de données reconnues dans l'UE ».",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Le règlement renvoie aux États membres pour la fixation des sanctions, qui doivent être effectives, proportionnées et dissuasives." },
    ],
    articulations: "Le DGA est complémentaire du Data Act : le DGA crée les mécanismes de gouvernance et de confiance, tandis que le Data Act crée les obligations de partage. Le RGPD s'applique pleinement dès que des données personnelles sont concernées.",
    timeline: [
      { date: "30 mai 2022", event: "Adoption du règlement" },
      { date: "23 juin 2022", event: "Publication au Journal officiel" },
      { date: "24 sept. 2023", event: "Entrée en application" },
      { date: "2024–2026", event: "Mise en place progressive des espaces européens de données sectoriels" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R0868",
    updatedAt: "2025-04-29",
  },
  {
    id: "dataact",
    badge: "Data Act",
    cat: "Données",
    name: "Accès et partage des données",
    ref: "Règlement (UE) 2023/2854",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "Data Act",
    fullName: "Data Act — Règlement sur des règles harmonisées portant sur l'équité de l'accès aux données",
    nature: "reglement",
    natureNote: "Le Data Act est un règlement européen d'application directe. Il est entré en vigueur le 11 janvier 2024 et sera pleinement applicable à partir du 12 septembre 2025. Aucune transposition nationale n'est nécessaire.",
    context: "80 % des données industrielles générées dans l'UE ne sont jamais réutilisées. Les fabricants d'objets connectés conservent un accès exclusif aux données générées par leurs produits, empêchant les utilisateurs et les tiers d'y accéder. Le Data Act vise à corriger ce déséquilibre en créant un droit d'accès aux données pour les utilisateurs de produits connectés.",
    summary: "Le Data Act établit des règles harmonisées sur l'accès aux données générées par les produits connectés (IoT) et les services associés. Il crée un droit pour les utilisateurs d'accéder aux données générées par leurs appareils connectés et de les partager avec des tiers. Le règlement facilite également le changement de fournisseur de services cloud en imposant des obligations de portabilité.",
    champ: "Fabricants de produits connectés (IoT), utilisateurs de ces produits, destinataires de données, fournisseurs de services de traitement de données (cloud, SaaS), organismes du secteur public demandant l'accès à des données privées en cas de nécessité exceptionnelle.",
    actors: [
      "Fabricants de produits connectés (IoT)",
      "Fournisseurs de services liés à un produit connecté",
      "Utilisateurs de produits connectés",
      "Fournisseurs de services cloud, edge et SaaS",
      "Organismes du secteur public",
    ],
    obligations: [
      "<strong>Accès aux données IoT (chapitre II, art. 3-7)</strong> — les fabricants doivent concevoir leurs produits de sorte que les données générées soient accessibles à l'utilisateur, facilement, gratuitement et dans un format structuré.",
      "<strong>Obligations B2B (chapitre III)</strong> — conditions FRAND (équitables, raisonnables et non discriminatoires). Les clauses contractuelles abusives sont interdites.",
      "<strong>Accès du secteur public (chapitre V)</strong> — en cas de nécessité exceptionnelle (urgence publique, catastrophe), les organismes publics peuvent demander l'accès aux données privées.",
      "<strong>Changement de fournisseur cloud (chapitre VI)</strong> — suppression progressive des frais de transfert, interopérabilité, portabilité des données.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Le règlement renvoie aux États membres. Les clauses contractuelles abusives sont nulles de plein droit." },
    ],
    articulations: "Le Data Act est complémentaire du DGA : le DGA crée les structures de gouvernance, le Data Act crée les obligations de partage. Le RGPD prévaut dès que des données personnelles sont en jeu.",
    timeline: [
      { date: "13 déc. 2023", event: "Adoption du règlement" },
      { date: "11 janv. 2024", event: "Entrée en vigueur" },
      { date: "12 sept. 2025", event: "Application de la plupart des dispositions" },
      { date: "12 sept. 2026", event: "Application des obligations de portabilité cloud" },
      { date: "12 sept. 2027", event: "Application des exigences d'interopérabilité cloud" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R2854",
    updatedAt: "2025-04-29",
  },
  {
    id: "dsa",
    badge: "DSA",
    cat: "Plateformes",
    name: "Services numériques",
    ref: "Règlement (UE) 2022/2065",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DSA",
    fullName: "Digital Services Act — Règlement sur les services numériques",
    nature: "reglement",
    natureNote: "Le DSA est un règlement européen d'application directe dans tous les États membres depuis le 17 février 2024. Chaque État membre doit désigner un Coordinateur des services numériques (CSN). En France, c'est l'Arcom.",
    context: "Le DSA remplace la directive e-commerce de 2000, adoptée à une époque où les plateformes en ligne n'existaient pas sous leur forme actuelle. En vingt ans, les plateformes sont devenues des acteurs systémiques de l'espace public numérique, posant des problèmes de désinformation, de contenus illicites, de manipulation algorithmique et de publicité ciblée opaque.",
    summary: "Le DSA établit un cadre harmonisé pour la responsabilité des services intermédiaires en ligne selon une architecture à plusieurs niveaux : obligations de base pour tous les intermédiaires, renforcées pour les hébergeurs, encore plus pour les plateformes, et maximales pour les très grandes plateformes (VLOP, +45 millions d'utilisateurs/mois dans l'UE).",
    champ: "Services intermédiaires accessibles aux utilisateurs dans l'UE : FAI, CDN, hébergeurs, plateformes en ligne (réseaux sociaux, marketplaces, app stores), très grandes plateformes (VLOP) et très grands moteurs de recherche (VLOSE). Seuil VLOP/VLOSE : 45 millions d'utilisateurs actifs mensuels dans l'UE.",
    actors: [
      "Fournisseurs de services intermédiaires (FAI, hébergeurs, CDN)",
      "Plateformes en ligne (réseaux sociaux, marketplaces, app stores)",
      "VLOP désignées : Meta (Facebook, Instagram), TikTok, X, YouTube, Amazon",
      "VLOSE désignés : Google Search, Bing",
      "Coordinateurs des services numériques (Arcom en France)",
      "Commission européenne (supervision directe des VLOP/VLOSE)",
    ],
    obligations: [
      "<strong>Transparence (art. 15, 24)</strong> — tous les intermédiaires doivent publier des rapports de transparence sur la modération de contenu.",
      "<strong>Notification et retrait (art. 16)</strong> — les hébergeurs doivent mettre en place des mécanismes de signalement de contenus illicites et agir promptement.",
      "<strong>Traçabilité des vendeurs (art. 30)</strong> — les marketplaces doivent identifier et vérifier les vendeurs professionnels (KYBC).",
      "<strong>Transparence de la publicité (art. 26-28)</strong> — interdiction de publicité ciblée fondée sur des données sensibles ou destinée aux mineurs.",
      "<strong>Systèmes de recommandation (art. 27)</strong> — les VLOP doivent proposer au moins une option sans profilage.",
      "<strong>Évaluation des risques systémiques (art. 34-35)</strong> — VLOP/VLOSE : analyse annuelle des risques et mesures d'atténuation.",
      "<strong>Accès aux données pour les chercheurs (art. 40)</strong> — VLOP/VLOSE doivent donner accès à leurs données aux chercheurs agréés.",
    ],
    sanctions: [
      { amount: "6 % du CA annuel mondial", detail: "Pour les infractions aux obligations du DSA" },
      { amount: "1 % du CA annuel mondial", detail: "Pour fourniture d'informations incorrectes ou refus d'inspection" },
      { amount: "5 % du CA journalier mondial", detail: "Astreintes journalières en cas de non-conformité persistante" },
      { amount: "Suspension du service", detail: "En cas de violations graves et persistantes (art. 52)" },
    ],
    articulations: "Le DSA coexiste avec le DMA (DSA régule les contenus, DMA régule la concurrence). Le RGPD s'applique pour les données personnelles dans la modération et la publicité ciblée. La directive e-commerce est abrogée en partie.",
    timeline: [
      { date: "19 oct. 2022", event: "Entrée en vigueur du règlement" },
      { date: "25 août 2023", event: "Application aux VLOP et VLOSE désignés" },
      { date: "17 fév. 2024", event: "Application à tous les fournisseurs de services intermédiaires" },
      { date: "2024–2026", event: "Premières procédures d'enquête (X/Twitter, TikTok, Meta, AliExpress, Temu)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2065",
    updatedAt: "2025-04-29",
  },
  {
    id: "dma",
    badge: "DMA",
    cat: "Plateformes",
    name: "Marchés numériques",
    ref: "Règlement (UE) 2022/1925",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DMA",
    fullName: "Digital Markets Act — Règlement sur les marchés numériques",
    nature: "reglement",
    natureNote: "Le DMA est un règlement européen d'application directe depuis le 2 mai 2023. Son application est centralisée : la Commission européenne est seule compétente pour désigner les contrôleurs d'accès et assurer l'application.",
    context: "Les plus grandes plateformes numériques (GAFAM) occupent des positions de contrôle d'accès (gatekeeper) sur des marchés clés : systèmes d'exploitation, navigateurs, app stores, moteurs de recherche, réseaux sociaux. Le droit de la concurrence classique s'est révélé trop lent. Le DMA adopte une approche ex ante : il impose directement des obligations aux contrôleurs d'accès désignés.",
    summary: "Le DMA vise à garantir la contestabilité et l'équité des marchés numériques en imposant des obligations ex ante aux contrôleurs d'accès (gatekeepers). Un gatekeeper fournit un service de plateforme essentiel avec un impact significatif sur le marché intérieur (CA ≥ 7,5 Mds€ ou capitalisation ≥ 75 Mds€) et une position durable (≥ 45 millions d'utilisateurs/mois dans l'UE).",
    champ: "Entreprises désignées comme contrôleurs d'accès par la Commission. En septembre 2023 : Alphabet (Google), Amazon, Apple, ByteDance (TikTok), Meta et Microsoft. 22 services de plateforme essentiels concernés.",
    actors: [
      "Contrôleurs d'accès désignés (Alphabet, Amazon, Apple, ByteDance, Meta, Microsoft)",
      "Entreprises utilisatrices des services de plateforme essentielle",
      "Utilisateurs finaux",
      "Commission européenne (application exclusive)",
      "Autorités nationales de concurrence (rôle de soutien)",
    ],
    obligations: [
      "<strong>Interdiction d'auto-préférence (art. 6§5)</strong> — un contrôleur d'accès ne peut pas favoriser ses propres produits dans les classements par rapport à ceux de tiers.",
      "<strong>Interopérabilité des messageries (art. 7)</strong> — les services de messagerie doivent permettre l'interopérabilité avec des services tiers.",
      "<strong>Liberté de désinstallation et de choix (art. 6§3-4)</strong> — les utilisateurs doivent pouvoir désinstaller les apps préinstallées et changer les paramètres par défaut.",
      "<strong>Interdiction du couplage de données (art. 5§2)</strong> — interdiction de combiner les données personnelles de différents services sans consentement explicite.",
      "<strong>Conditions équitables pour les app stores (art. 5§4)</strong> — autoriser les développeurs à diriger vers des canaux de distribution alternatifs (sideloading).",
      "<strong>Portabilité et accès aux données (art. 6§9-10)</strong> — les utilisateurs peuvent accéder à leurs données et les porter vers d'autres services.",
    ],
    sanctions: [
      { amount: "10 % du CA mondial", detail: "Pour non-respect des obligations ou interdictions du DMA" },
      { amount: "20 % du CA mondial", detail: "En cas de récidive (infraction systématique)" },
      { amount: "5 % du CA journalier mondial", detail: "Astreintes journalières" },
      { amount: "Remèdes structurels", detail: "En cas de non-conformité systématique, cession d'activités possible (art. 18)" },
    ],
    articulations: "Le DMA est complémentaire du DSA : le DMA régule la concurrence, le DSA régule les contenus. Le règlement P2B (2019/1150) est le précurseur du DMA. Le DMA interagit avec le RGPD pour le couplage de données.",
    timeline: [
      { date: "1er nov. 2022", event: "Entrée en vigueur du règlement" },
      { date: "2 mai 2023", event: "Début de l'application" },
      { date: "6 sept. 2023", event: "Désignation des 6 premiers contrôleurs d'accès" },
      { date: "6 mars 2024", event: "Date limite de mise en conformité" },
      { date: "2024–2026", event: "Premières enquêtes de conformité (Apple, Alphabet, Meta)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R1925",
    updatedAt: "2025-04-29",
  },
  {
    id: "p2b",
    badge: "P2B",
    cat: "Plateformes",
    name: "Relations plateformes–entreprises",
    ref: "Règlement (UE) 2019/1150",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "P2B",
    fullName: "Platform-to-Business — Règlement promouvant l'équité et la transparence pour les entreprises",
    nature: "reglement",
    natureNote: "Le P2B est un règlement européen d'application directe depuis le 12 juillet 2020. Il a été en partie supplanté par le DMA pour les plus grandes plateformes, mais reste applicable à toutes les plateformes d'intermédiation.",
    context: "Les PME et commerçants qui vendent via des plateformes (Amazon, Booking, App Store) se trouvent dans une situation de dépendance économique : conditions générales modifiées unilatéralement, déréférencement sans préavis, manque de transparence sur les classements. Le P2B a été le premier texte européen à s'attaquer à ce déséquilibre.",
    summary: "Le règlement P2B impose des obligations de transparence et d'équité aux plateformes d'intermédiation dans leurs relations avec les entreprises utilisatrices. Les plateformes doivent rédiger des conditions claires, notifier à l'avance toute modification, expliquer les raisons de toute restriction, décrire les paramètres de classement, et déclarer tout traitement différencié de leurs propres offres.",
    champ: "Services d'intermédiation en ligne (marketplaces, app stores, plateformes de réservation, comparateurs) et moteurs de recherche, dès lors qu'ils ciblent des consommateurs dans l'UE. Le règlement s'applique quelle que soit la taille de la plateforme.",
    actors: [
      "Plateformes d'intermédiation en ligne (Amazon, Booking, Uber Eats, Google Play, App Store)",
      "Moteurs de recherche en ligne",
      "Entreprises utilisatrices (vendeurs, développeurs, hôteliers)",
      "Organisations représentatives et associations professionnelles",
    ],
    obligations: [
      "<strong>Conditions générales (art. 3)</strong> — les CGU doivent être claires et accessibles. Toute modification doit être notifiée avec un préavis d'au moins 15 jours.",
      "<strong>Motivation des restrictions (art. 4)</strong> — toute suspension ou résiliation de compte doit être motivée avant ou au moment de la prise d'effet.",
      "<strong>Transparence du classement (art. 5)</strong> — décrire les principaux paramètres de classement et leur importance relative. Déclarer si un paiement influence le classement.",
      "<strong>Traitement différencié (art. 7)</strong> — déclarer si la plateforme accorde un traitement différencié à ses propres offres.",
      "<strong>Système de réclamations (art. 11)</strong> — mécanisme interne de traitement des plaintes pour les plateformes de taille significative.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Le DMA a pris le relais pour les plus grandes plateformes avec des sanctions beaucoup plus lourdes." },
    ],
    articulations: "Le P2B est le précurseur du DMA, qui va beaucoup plus loin pour les contrôleurs d'accès. Le P2B reste applicable aux plateformes ne relevant pas du DMA.",
    timeline: [
      { date: "20 juin 2019", event: "Adoption du règlement" },
      { date: "12 juil. 2020", event: "Entrée en application" },
      { date: "2022", event: "Adoption du DMA, qui va plus loin pour les gatekeepers" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019R1150",
    updatedAt: "2025-04-29",
  },
  {
    id: "nis2",
    badge: "NIS 2",
    cat: "Cybersécurité",
    name: "Sécurité des réseaux et systèmes",
    ref: "Directive (UE) 2022/2555",
    type: "Directive",
    status: "partial",
    statusLabel: "Transposition en cours",
    title: "NIS 2",
    fullName: "Directive sur un niveau élevé commun de cybersécurité dans l'Union",
    nature: "directive",
    natureNote: "NIS 2 est une directive nécessitant une transposition nationale. Le délai était le 17 octobre 2024. En France, le projet de loi « Résilience » a été adopté par le Sénat le 12 mars 2025 mais le vote à l'Assemblée nationale est reporté à juillet 2026. La Commission a envoyé un avis motivé à la France en mai 2025.",
    context: "La directive NIS 1 de 2016 avait un périmètre très restreint (environ 300 entités en France) et une application hétérogène. Face à l'augmentation massive des cyberattaques, l'UE a décidé de remplacer NIS 1 par un cadre beaucoup plus ambitieux. NIS 2 multiplie par 50 le nombre d'entités concernées en France (de 300 à 15 000-18 000).",
    summary: "La directive NIS 2 renforce le cadre de cybersécurité européen en élargissant son champ à 18 secteurs (contre 7 pour NIS 1), en introduisant des obligations de gestion des risques plus strictes, et en responsabilisant personnellement les dirigeants. Elle crée deux catégories : entités essentielles (EE) et entités importantes (EI), soumises à des régimes de supervision différenciés.",
    champ: "18 secteurs répartis en entités essentielles (énergie, transport, santé, eau, infrastructures numériques, administrations publiques, espace) et entités importantes (services postaux, gestion des déchets, industrie chimique, agroalimentaire, fabrication, fournisseurs numériques, recherche). Critères : entreprises de plus de 50 salariés ou CA/bilan > 10 M€.",
    actors: [
      "Entités essentielles (EE) et entités importantes (EI) dans les 18 secteurs couverts",
      "ANSSI (autorité nationale compétente en France)",
      "CSIRT nationaux (centres de réponse aux incidents)",
      "Réseau CyCLONe (coordination des crises cyber au niveau européen)",
      "ENISA (Agence de l'UE pour la cybersécurité)",
      "Dirigeants des entités concernées (responsabilité personnelle)",
    ],
    obligations: [
      "<strong>Mesures de gestion des risques (art. 21)</strong> — analyse de risques, gestion des incidents, continuité d'activité, sécurité de la chaîne d'approvisionnement, MFA, chiffrement, formation du personnel.",
      "<strong>Notification des incidents (art. 23)</strong> — alerte initiale dans les 24 heures, notification complète dans les 72 heures, rapport final dans un mois.",
      "<strong>Responsabilité des dirigeants (art. 20)</strong> — les organes de direction doivent approuver les mesures de cybersécurité et suivre des formations. Responsabilité personnelle possible.",
      "<strong>Enregistrement (art. 3, 27)</strong> — les entités concernées doivent s'enregistrer auprès de l'autorité compétente nationale.",
      "<strong>Sécurité de la chaîne d'approvisionnement (art. 21§2(d))</strong> — évaluer et gérer les risques liés aux fournisseurs et prestataires.",
    ],
    sanctions: [
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour les entités essentielles" },
      { amount: "7 M€ ou 1,4 % du CA mondial", detail: "Pour les entités importantes" },
      { amount: "Responsabilité personnelle des dirigeants", detail: "Possibilité d'interdictions temporaires d'exercer pour les dirigeants d'entités essentielles" },
    ],
    articulations: "NIS 2 s'articule avec le CRA (exigences de cybersécurité aux produits), le Cybersecurity Act (certification), DORA (lex specialis pour le secteur financier — les entités financières soumises à DORA sont exemptées de NIS 2).",
    timeline: [
      { date: "14 déc. 2022", event: "Adoption de la directive" },
      { date: "17 oct. 2024", event: "Date limite de transposition (non respectée par la plupart des États membres)" },
      { date: "Mai 2025", event: "Avis motivé de la Commission à 19 États membres dont la France" },
      { date: "17 mars 2026", event: "Publication par l'ANSSI du Référentiel Cyber France (ReCyF)" },
      { date: "Juil. 2026 (prévu)", event: "Vote de la loi de transposition à l'Assemblée nationale" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022L2555",
    updatedAt: "2025-04-29",
  },
  {
    id: "cra",
    badge: "CRA",
    cat: "Cybersécurité",
    name: "Cyber-résilience des produits",
    ref: "Règlement (UE) 2024/2847",
    type: "Règlement",
    status: "upcoming",
    statusLabel: "Application progressive",
    title: "CRA",
    fullName: "Cyber Resilience Act — Exigences de cybersécurité pour les produits numériques",
    nature: "reglement",
    natureNote: "Le CRA est un règlement européen d'application directe. Entré en vigueur le 10 décembre 2024, avec application progressive jusqu'au 11 décembre 2027.",
    context: "Les produits connectés sont mis sur le marché avec des vulnérabilités connues, sans obligation de les corriger après la vente. Aucune réglementation horizontale n'existait pour imposer des exigences de cybersécurité aux fabricants. Le CRA applique au numérique la logique du marquage CE.",
    summary: "Le CRA impose pour la première fois des exigences de cybersécurité obligatoires à tous les produits comportant des éléments numériques mis sur le marché européen. Les fabricants doivent intégrer la sécurité dès la conception (security by design), assurer des mises à jour pendant la durée de vie du produit (minimum 5 ans), et signaler les vulnérabilités activement exploitées à l'ENISA dans les 24 heures.",
    champ: "Tous les produits comportant des éléments numériques : objets connectés (IoT), logiciels, matériel informatique (routeurs, smartphones, ordinateurs). Sont exclus : dispositifs médicaux, aviation, véhicules, produits exclusivement destinés à la défense nationale.",
    actors: [
      "Fabricants de produits comportant des éléments numériques",
      "Importateurs et distributeurs",
      "ENISA (coordination des signalements de vulnérabilités)",
      "Organismes d'évaluation de la conformité (organismes notifiés)",
      "Autorités de surveillance du marché dans chaque État membre",
    ],
    obligations: [
      "<strong>Security by design (annexe I)</strong> — les produits doivent être conçus avec un niveau de cybersécurité approprié : protection contre les accès non autorisés, minimisation des surfaces d'attaque.",
      "<strong>Gestion des vulnérabilités</strong> — identifier et documenter les vulnérabilités, fournir des mises à jour gratuites pendant au moins 5 ans, politique coordonnée de divulgation.",
      "<strong>Signalement (art. 14)</strong> — notification à l'ENISA dans les 24 heures pour une vulnérabilité activement exploitée, notification complète dans les 72 heures.",
      "<strong>Marquage CE</strong> — selon la catégorie du produit, auto-évaluation ou évaluation par un organisme tiers.",
      "<strong>SBOM</strong> — les fabricants doivent établir et maintenir une nomenclature des composants logiciels.",
    ],
    sanctions: [
      { amount: "15 M€ ou 2,5 % du CA mondial", detail: "Pour non-respect des exigences essentielles de cybersécurité" },
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour non-respect des autres obligations (signalement, documentation)" },
      { amount: "5 M€ ou 1 % du CA mondial", detail: "Pour fourniture d'informations incorrectes aux autorités" },
    ],
    articulations: "Le CRA complète NIS 2 : NIS 2 impose des obligations aux entités (organisations), le CRA aux produits. Il interagit avec le Cybersecurity Act pour la certification et avec le Data Act pour l'accès aux données des produits connectés.",
    timeline: [
      { date: "12 mars 2024", event: "Adoption par le Parlement européen" },
      { date: "10 déc. 2024", event: "Entrée en vigueur" },
      { date: "11 sept. 2026", event: "Application des obligations de signalement des vulnérabilités" },
      { date: "11 déc. 2027", event: "Application de l'ensemble des obligations (security by design, marquage CE)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R2847",
    updatedAt: "2025-04-29",
  },
  {
    id: "cybersecact",
    badge: "CSA",
    cat: "Cybersécurité",
    name: "Certification de cybersécurité",
    ref: "Règlement (UE) 2019/881",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "Cybersecurity Act",
    fullName: "Cybersecurity Act — Règlement relatif à l'ENISA et à la certification de cybersécurité",
    nature: "reglement",
    natureNote: "Le Cybersecurity Act est un règlement européen d'application directe depuis le 27 juin 2019. Il ne nécessite aucune transposition nationale.",
    context: "Avant le Cybersecurity Act, il n'existait pas de cadre européen unifié pour la certification de cybersécurité. Chaque État membre avait ses propres schémas nationaux (CSPN en France, BSI en Allemagne), créant une fragmentation coûteuse pour les entreprises.",
    summary: "Le Cybersecurity Act renforce le mandat de l'ENISA (qui devient une agence permanente) et crée un cadre européen de certification de cybersécurité volontaire pour les produits, services et processus TIC, avec trois niveaux d'assurance (élémentaire, substantiel, élevé).",
    champ: "Produits, services et processus TIC mis sur le marché de l'UE. Organismes nationaux d'accréditation et d'évaluation de la conformité.",
    actors: [
      "ENISA (rôle central dans la préparation des schémas et la coordination)",
      "Commission européenne (adoption des schémas par actes d'exécution)",
      "Autorités nationales de certification (ANSSI en France)",
      "Organismes d'évaluation de la conformité",
      "Fabricants et fournisseurs de produits/services TIC",
    ],
    obligations: [
      "<strong>Schémas européens de certification (art. 46-65)</strong> — l'ENISA prépare des schémas candidats. Chaque schéma définit les produits/services couverts, les exigences et les méthodes d'évaluation.",
      "<strong>Trois niveaux d'assurance (art. 52)</strong> — élémentaire (auto-évaluation), substantiel (évaluation par tiers), élevé (organisme accrédité avec tests de pénétration).",
      "<strong>Reconnaissance mutuelle (art. 56)</strong> — un certificat délivré dans un État membre est reconnu dans tous les autres.",
      "<strong>ENISA renforcée</strong> — mandat permanent, assistance technique, coordination des incidents à grande échelle.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Sanctions pour utilisation frauduleuse de certificats ou non-respect des obligations de certification." },
    ],
    articulations: "Le Cybersecurity Act fournit le cadre de certification utilisé par NIS 2 et le CRA. Il interagit aussi avec le RGPD pour la certification en matière de protection des données (art. 42 RGPD).",
    timeline: [
      { date: "17 avril 2019", event: "Adoption du règlement" },
      { date: "27 juin 2019", event: "Entrée en vigueur" },
      { date: "2020", event: "Premier schéma de certification adopté : EUCC (critères communs européens)" },
      { date: "2024–2026", event: "Schémas en cours : EUCS (cloud), EU5G (réseaux 5G)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019R0881",
    updatedAt: "2025-04-29",
  },
  {
    id: "aiact",
    badge: "AI Act",
    cat: "IA",
    name: "Intelligence artificielle",
    ref: "Règlement (UE) 2024/1689",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "AI Act",
    fullName: "Règlement établissant des règles harmonisées concernant l'intelligence artificielle",
    nature: "reglement",
    natureNote: "L'AI Act est un règlement européen d'application directe, entré en vigueur le 1er août 2024. Il s'applique de manière progressive depuis février 2025 et devrait s'appliquer entièrement d'ici août 2027. En France, la CNIL, la DGCCRF et l'Arcom se partagent les compétences.",
    context: "L'AI Act est le premier cadre juridique au monde dédié à la régulation de l'intelligence artificielle. Proposé en avril 2021, avant l'explosion de l'IA générative (ChatGPT, fin 2022), il a conduit à des ajouts importants sur les modèles d'IA à usage général (GPAI). Il adopte une approche fondée sur le risque.",
    summary: "L'AI Act encadre le développement, la mise sur le marché et l'utilisation des systèmes d'IA selon quatre niveaux de risque. Les pratiques à risque inacceptable sont interdites. Les systèmes à haut risque (recrutement, crédit, justice, éducation, biométrie) ont des obligations strictes. Les modèles GPAI à risque systémique ont des obligations renforcées.",
    champ: "Il s'applique à tout fournisseur développant ou mettant sur le marché un système d'IA dans l'UE, à tout déployeur professionnel, et à tout fournisseur hors UE dont le système produit des résultats utilisés dans l'UE. Sont exclus : la recherche scientifique sans objectif commercial, les systèmes militaires et les utilisations purement personnelles.",
    actors: [
      "Fournisseurs de systèmes d'IA (développeurs, éditeurs)",
      "Déployeurs (entreprises et organisations utilisant des systèmes d'IA)",
      "Fournisseurs de modèles GPAI (OpenAI, Google, Meta, Mistral, etc.)",
      "Bureau européen de l'IA (AI Office, au sein de la Commission)",
      "Autorités nationales compétentes (CNIL, DGCCRF, Arcom en France)",
    ],
    obligations: [
      "<div style=\"margin:8px 0 12px;\"><p style=\"font-weight:600;margin-bottom:10px;\">Pyramide des risques de l'AI Act :</p><div style=\"display:flex;flex-direction:column;align-items:center;gap:3px;max-width:440px;\"><div style=\"background:#fee2e2;border:1px solid #fca5a5;border-radius:6px;padding:7px 14px;text-align:center;width:38%;font-size:12px;font-weight:600;color:#991b1b;\">🚫 Risque inacceptable<br><span style=\"font-weight:400;font-size:11px;\">Pratiques interdites (art. 5)</span></div><div style=\"background:#ffedd5;border:1px solid #fdba74;border-radius:6px;padding:7px 14px;text-align:center;width:58%;font-size:12px;font-weight:600;color:#9a3412;\">⚠️ Haut risque<br><span style=\"font-weight:400;font-size:11px;\">Obligations strictes (art. 6-51)</span></div><div style=\"background:#fef9c3;border:1px solid #fde047;border-radius:6px;padding:7px 14px;text-align:center;width:78%;font-size:12px;font-weight:600;color:#713f12;\">💬 Risque limité<br><span style=\"font-weight:400;font-size:11px;\">Obligations de transparence (art. 50)</span></div><div style=\"background:#dcfce7;border:1px solid #86efac;border-radius:6px;padding:7px 14px;text-align:center;width:100%;font-size:12px;font-weight:600;color:#14532d;\">✅ Risque minimal<br><span style=\"font-weight:400;font-size:11px;\">Aucune obligation spécifique</span></div></div></div>",
      "<strong>Interdictions (art. 5)</strong> : scoring social par les autorités publiques, manipulation subliminale ou exploitation des vulnérabilités, identification biométrique à distance en temps réel dans l'espace public (sauf exceptions strictes telles que la recherche d'un enfant disparu ou la prévention d'une menace terroriste imminente).",
      "<strong>Systèmes à haut risque (chapitre III)</strong> : gestion des risques, gouvernance des données d'entraînement, documentation technique, journalisation automatique, supervision humaine, exactitude et robustesse, marquage CE, inscription dans la base de données européenne de l'IA.",
      "<strong>Obligations de transparence (art. 50)</strong> : les systèmes d'IA interagissant avec des personnes (chatbots) doivent informer les utilisateurs qu'ils interagissent avec une IA. Par exemple, le chatbot « Amélie » de l'Assurance Maladie doit afficher clairement qu'il s'agit d'un assistant automatisé. Les contenus générés par IA (textes, images, sons) et les deepfakes doivent être étiquetés comme tels.",
      "<strong>Modèles GPAI — General Purpose AI (chapitre V)</strong> : les modèles GPAI sont des modèles d'IA entraînés sur de grandes quantités de données, capables de réaliser de nombreuses tâches différentes (comme les grands modèles de langage GPT, Claude ou Gemini). Leurs obligations comprennent : documentation technique, respect du droit d'auteur, publication d'un résumé des données d'entraînement. Pour les modèles à risque systémique : évaluation des risques, tests adversariaux, signalement des incidents graves à l'AI Office.",
      "<strong>Bacs à sable réglementaires (art. 57)</strong> : un bac à sable réglementaire est un environnement contrôlé et supervisé permettant à des fournisseurs de tester et valider leurs systèmes d'IA avant leur mise sur le marché, sous la surveillance des autorités compétentes. Chaque État membre doit mettre en place au moins un bac à sable réglementaire d'ici le 2 août 2026.",
    ],
    sanctionsIntro: "Les sanctions prévues par l'AI Act varient selon la nature de la non-conformité et la catégorie d'entreprise. Elles sont déterminées soit en pourcentage du chiffre d'affaires annuel mondial, soit sur la base de seuils absolus, en retenant le montant le plus élevé.",
    sanctions: [
      { amount: "35 M€ ou 7 % du CA mondial", detail: "Pour violation des pratiques interdites (art. 5 : notation sociale, manipulation subliminale, identification biométrique non autorisée)" },
      { amount: "15 M€ ou 3 % du CA mondial", detail: "Pour manquement aux exigences applicables aux systèmes à haut risque et aux obligations des fournisseurs, déployeurs et représentants autorisés" },
      { amount: "7,5 M€ ou 1 % du CA mondial", detail: "Pour non-conformité aux exigences de transparence (risque limité) et pour fourniture d'informations incorrectes ou trompeuses aux autorités" },
      { amount: "Sanctions réduites pour PME et start-ups", detail: "Pour les PME et start-ups, les amendes sont plafonnées au montant le plus faible entre le pourcentage du chiffre d'affaires et le seuil absolu, afin de garantir leur proportionnalité et de ne pas entraver l'innovation." },
    ],
    articulations: "L'AI Act s'articule étroitement avec le RGPD pour le traitement des données personnelles dans l'entraînement et le déploiement. Le CRA s'applique aux systèmes d'IA embarqués dans des produits connectés. La directive droit d'auteur (art. 3-4 sur l'exception TDM) est pertinente pour les données d'entraînement.",
    timeline: [
      { date: "13 mars 2024", event: "Adoption par le Parlement européen" },
      { date: "1er août 2024", event: "Entrée en vigueur" },
      { date: "2 fév. 2025", event: "Interdiction des pratiques d'IA à risque inacceptable" },
      { date: "2 août 2025", event: "Obligations pour les modèles GPAI, désignation des autorités nationales" },
      { date: "2 août 2026", event: "Application complète pour les systèmes à haut risque (annexe III)" },
      { date: "2 août 2027", event: "Application aux systèmes intégrés dans des produits réglementés" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    updatedAt: "2025-04-29",
  },
  {
    id: "dora",
    badge: "DORA",
    cat: "Finance",
    name: "Résilience opérationnelle numérique",
    ref: "Règlement (UE) 2022/2554",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DORA",
    fullName: "Digital Operational Resilience Act — Résilience opérationnelle numérique du secteur financier",
    nature: "reglement",
    natureNote: "DORA est un règlement européen d'application directe depuis le 17 janvier 2025. Il est la lex specialis en matière de cybersécurité pour le secteur financier — les entités soumises à DORA sont exemptées de NIS 2.",
    context: "Le secteur financier est l'un des plus exposés aux risques cyber. Les incidents informatiques dans les banques peuvent provoquer des crises systémiques. Avant DORA, les exigences de résilience numérique étaient fragmentées entre diverses directives sectorielles. DORA crée un cadre unique et horizontal.",
    summary: "DORA impose des exigences uniformes de résilience opérationnelle numérique à l'ensemble des entités financières de l'UE. Il couvre cinq piliers : gestion des risques TIC, gestion et signalement des incidents TIC, tests de résilience (dont tests de pénétration avancés TLPT), gestion des risques liés aux prestataires tiers, et partage d'informations sur les cybermenaces.",
    champ: "Plus de 20 types d'entités financières : établissements de crédit, entreprises d'investissement, assurances, fonds de pension, prestataires de services sur crypto-actifs (MiCA), etc. Également les prestataires tiers critiques de services TIC (cloud providers).",
    actors: [
      "Entités financières (banques, assurances, sociétés de gestion, PSP)",
      "Prestataires tiers critiques de services TIC (cloud, SaaS)",
      "Autorités européennes de surveillance (ABE, AEAPP, AEMF)",
      "Autorités nationales de supervision financière (ACPR, AMF en France)",
      "Superviseur principal (Lead Overseer) pour les prestataires tiers critiques",
    ],
    obligations: [
      "<strong>Gestion des risques TIC (chapitre II)</strong> — cadre complet : stratégie de résilience, politiques de sécurité, gestion des actifs TIC, détection des menaces, plans de continuité.",
      "<strong>Signalement des incidents (chapitre III)</strong> — classification selon des critères harmonisés. Signalement des incidents majeurs à l'autorité compétente.",
      "<strong>Tests de résilience (chapitre IV)</strong> — tests réguliers (vulnérabilités, pénétration). Tests de pénétration avancés TLPT tous les 3 ans pour les entités importantes.",
      "<strong>Risques liés aux tiers (chapitre V)</strong> — clauses minimales dans les contrats TIC (accès, audit, sécurité, portabilité). Supervision directe des prestataires critiques.",
    ],
    sanctions: [
      { amount: "Définies par les États membres et les AES", detail: "Selon les cadres sectoriels financiers existants" },
      { amount: "Astreintes pour les prestataires tiers critiques", detail: "1 % du CA mondial quotidien moyen pour les prestataires non conformes" },
    ],
    articulations: "DORA est la lex specialis de NIS 2 pour le secteur financier. Il interagit avec MiCA pour les prestataires de services sur crypto-actifs et avec le RGPD pour la notification des incidents impliquant des données personnelles.",
    timeline: [
      { date: "14 déc. 2022", event: "Adoption du règlement" },
      { date: "16 janv. 2023", event: "Entrée en vigueur" },
      { date: "17 janv. 2025", event: "Application de l'ensemble des dispositions" },
      { date: "2025–2026", event: "Premiers cycles de tests TLPT et désignation des prestataires tiers critiques" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2554",
    updatedAt: "2025-04-29",
  },
  {
    id: "mica",
    badge: "MiCA",
    cat: "Finance",
    name: "Marchés de crypto-actifs",
    ref: "Règlement (UE) 2023/1114",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "MiCA",
    fullName: "Markets in Crypto-Assets — Règlement sur les marchés de crypto-actifs",
    nature: "reglement",
    natureNote: "MiCA est un règlement européen d'application directe. Les dispositions sur les stablecoins sont applicables depuis le 30 juin 2024, et l'ensemble du règlement depuis le 30 décembre 2024.",
    context: "Le marché des crypto-actifs s'est développé en marge du cadre réglementaire financier, entraînant des risques importants pour les investisseurs (escroqueries, faillites comme FTX). MiCA est le premier cadre juridique complet au monde pour les crypto-actifs, créant un « passeport européen » pour les prestataires.",
    summary: "MiCA établit un cadre juridique harmonisé pour l'émission et la négociation de crypto-actifs dans l'UE. Il distingue trois catégories : jetons référencés à des actifs (ART — stablecoins), jetons de monnaie électronique (EMT), et autres crypto-actifs. Les prestataires de services (CASP) doivent obtenir un agrément auprès de leur autorité nationale (AMF en France).",
    champ: "Émetteurs de crypto-actifs (ART, EMT, utility tokens), prestataires de services sur crypto-actifs (CASP : plateformes d'échange, services de conservation, conseil). Sont exclus : crypto-actifs qualifiés d'instruments financiers (MiFID II), NFT uniques.",
    actors: [
      "Émetteurs de crypto-actifs (projets blockchain, émetteurs de stablecoins)",
      "Prestataires de services sur crypto-actifs (CASP — Binance, Coinbase, Kraken)",
      "Autorité bancaire européenne (ABE — supervision des ART et EMT significatifs)",
      "Autorités nationales compétentes (AMF en France pour les CASP)",
      "Investisseurs et détenteurs de crypto-actifs",
    ],
    obligations: [
      "<strong>Livre blanc (art. 6, 17, 51)</strong> — tout émetteur doit publier un livre blanc décrivant le projet, les risques et les droits associés.",
      "<strong>Réserve d'actifs pour les ART (art. 36-39)</strong> — maintenir une réserve liquide couvrant 100 % des jetons émis, avec des règles strictes de composition et de transparence.",
      "<strong>Agrément des CASP (art. 59-63)</strong> — obtenir un agrément auprès de l'autorité nationale, valable dans toute l'UE (passeport européen).",
      "<strong>Obligations de conduite (art. 66-82)</strong> — agir loyalement, informer sur les risques, séparer les actifs des clients des actifs propres.",
      "<strong>Prévention des abus de marché (titre VI)</strong> — interdiction des opérations d'initiés, de la manipulation de marché.",
    ],
    sanctions: [
      { amount: "Jusqu'à 5 M€ ou 3-12,5 % du CA", detail: "Selon le type d'infraction et les choix nationaux" },
      { amount: "Retrait d'agrément", detail: "En cas de manquement grave" },
    ],
    articulations: "MiCA s'articule avec DORA pour les exigences de résilience numérique des CASP. Le RGPD s'applique au traitement des données personnelles des clients. La directive anti-blanchiment s'applique pour la lutte contre le blanchiment.",
    timeline: [
      { date: "9 juin 2023", event: "Adoption du règlement" },
      { date: "30 juin 2024", event: "Application des titres III et IV (ART et EMT)" },
      { date: "30 déc. 2024", event: "Application complète (CASP, abus de marché)" },
      { date: "2025–2026", event: "Période transitoire pour les CASP existants (agrément à obtenir)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R1114",
    updatedAt: "2025-04-29",
  },
  {
    id: "eidas2",
    badge: "eIDAS 2",
    cat: "Identité",
    name: "Identité numérique européenne",
    ref: "Règlement (UE) 2024/1183",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "eIDAS 2",
    fullName: "Règlement modifiant eIDAS — Portefeuille européen d'identité numérique (EUDIW)",
    nature: "reglement",
    natureNote: "eIDAS 2 est un règlement européen d'application directe, entré en vigueur le 20 mai 2024. Les États membres doivent mettre à disposition le portefeuille d'identité numérique (EUDIW) d'ici mai 2026.",
    context: "Le règlement eIDAS de 2014 avait créé un cadre pour la reconnaissance mutuelle des identités numériques entre États membres, mais l'adoption est restée faible : seuls 14 % des citoyens disposaient d'une identité numérique reconnue transfrontalièrement. eIDAS 2 ambitionne de créer un portefeuille d'identité numérique européen accessible à tous.",
    summary: "eIDAS 2 modernise le cadre d'identité numérique en créant le portefeuille européen d'identité numérique (EUDIW). Chaque État membre devra fournir gratuitement un portefeuille à ses citoyens permettant de s'identifier en ligne, stocker des attributs vérifiables (diplômes, permis, prescriptions) et signer électroniquement — avec divulgation sélective des données.",
    champ: "États membres (obligation de fournir le portefeuille), services publics nationaux (acceptation obligatoire), très grandes plateformes en ligne au sens du DSA (acceptation obligatoire pour l'authentification), prestataires de services de confiance qualifiés.",
    actors: [
      "États membres (émetteurs du portefeuille EUDIW)",
      "Citoyens et résidents de l'UE (utilisateurs du portefeuille)",
      "Services publics (acceptation obligatoire)",
      "Très grandes plateformes — VLOP (acceptation obligatoire)",
      "Prestataires de services de confiance qualifiés",
    ],
    obligations: [
      "<strong>Mise à disposition du portefeuille (art. 5a)</strong> — chaque État membre doit fournir gratuitement un portefeuille d'identité numérique à ses citoyens et résidents.",
      "<strong>Acceptation obligatoire (art. 5b)</strong> — les services publics et les VLOP doivent accepter le portefeuille EUDIW pour l'authentification.",
      "<strong>Divulgation sélective et pseudonymat</strong> — le portefeuille permet de prouver des attributs sans divulguer l'identité complète.",
      "<strong>Signature électronique qualifiée intégrée</strong> — fonctionnalité de signature accessible gratuitement pour les usages non professionnels.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Renvoyées aux régimes nationaux de supervision des prestataires de services de confiance" },
    ],
    articulations: "eIDAS 2 s'articule avec le DSA (les VLOP doivent accepter le portefeuille), le RGPD (minimisation et contrôle de l'utilisateur), et NIS 2 (les prestataires de services de confiance sont des entités essentielles).",
    timeline: [
      { date: "20 mai 2024", event: "Entrée en vigueur" },
      { date: "Nov. 2024", event: "Publication de l'Architecture Reference Framework (ARF) v1.4" },
      { date: "Mai 2026", event: "Délai pour la mise à disposition du portefeuille EUDIW par les États membres" },
      { date: "2026–2027", event: "Déploiement progressif et certification des portefeuilles" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1183",
    updatedAt: "2025-04-29",
  },
  {
    id: "copyright",
    badge: "Dir. ©",
    cat: "Droits num.",
    name: "Droit d'auteur numérique",
    ref: "Directive (UE) 2019/790",
    type: "Directive",
    status: "transposed",
    statusLabel: "Transposée",
    title: "Directive droit d'auteur",
    fullName: "Directive sur le droit d'auteur et les droits voisins dans le marché unique numérique",
    nature: "directive",
    natureNote: "Directive transposée en France par l'ordonnance n° 2021-580 du 12 mai 2021 et la loi du 24 juin 2020 (droit voisin des éditeurs de presse). C'est la loi française qui s'applique directement.",
    context: "Le droit d'auteur européen n'avait pas été substantiellement réformé depuis 2001. Les plateformes de partage (YouTube, TikTok) sont devenues les principaux canaux de diffusion, les agrégateurs captent la valeur du travail journalistique, et l'exploration de données (TDM) est un outil central pour l'IA.",
    summary: "Cette directive modernise le droit d'auteur autour de trois axes : un droit voisin pour les éditeurs de presse (rémunération par les agrégateurs), la responsabilité des plateformes de partage de contenu (obligation de licence ou de retrait), et des exceptions pour l'exploration de textes et données (TDM) cruciale pour l'entraînement des modèles d'IA.",
    champ: "Plateformes de partage de contenu (YouTube, Instagram, TikTok), éditeurs de presse, agrégateurs d'actualités, organismes de recherche, institutions culturelles. Exclus : encyclopédies en ligne à but non lucratif (Wikipedia), répertoires éducatifs, marketplaces.",
    actors: [
      "Plateformes de partage de contenu (YouTube, Instagram, TikTok)",
      "Éditeurs de presse (bénéficiaires du droit voisin)",
      "Agrégateurs d'actualités (Google News, Apple News)",
      "Auteurs, artistes-interprètes et producteurs",
      "Organismes de recherche (exception TDM)",
    ],
    obligations: [
      "<strong>Droit voisin des éditeurs de presse (art. 15)</strong> — les agrégateurs doivent obtenir une licence et rémunérer les éditeurs pour la réutilisation de publications de presse. Durée : 2 ans.",
      "<strong>Responsabilité des plateformes (art. 17)</strong> — les plateformes sont responsables des contenus protégés non autorisés, sauf si elles ont fait les meilleurs efforts pour obtenir des licences.",
      "<strong>Exception TDM pour la recherche (art. 3)</strong> — les organismes de recherche peuvent reproduire des contenus à des fins scientifiques sans autorisation.",
      "<strong>Exception TDM commerciale (art. 4)</strong> — autorisée sauf si les titulaires ont exercé leur droit d'opt-out. Crucial pour l'entraînement des modèles d'IA.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Selon les régimes nationaux de propriété intellectuelle (Code de la propriété intellectuelle en France)" },
    ],
    articulations: "La directive droit d'auteur interagit fortement avec l'AI Act : l'exception TDM est le cadre pour l'entraînement des modèles d'IA. L'AI Act impose aux fournisseurs de GPAI de respecter le droit d'auteur et de publier un résumé des données d'entraînement.",
    timeline: [
      { date: "17 avril 2019", event: "Adoption de la directive" },
      { date: "7 juin 2021", event: "Délai de transposition" },
      { date: "Mai 2021", event: "Transposition française (ordonnance n° 2021-580)" },
      { date: "2022–2026", event: "Contentieux sur le droit voisin (Google, Meta, négociations en cours)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019L0790",
    updatedAt: "2025-04-29",
  },
  {
    id: "eprivacy",
    badge: "ePrivacy",
    cat: "Droits num.",
    name: "Vie privée et communications",
    ref: "Directive 2002/58/CE",
    type: "Directive",
    status: "active",
    statusLabel: "En vigueur",
    title: "ePrivacy",
    fullName: "Directive vie privée et communications électroniques",
    nature: "directive",
    natureNote: "La directive ePrivacy est en vigueur depuis 2002, modifiée en 2009. Transposée en France dans le CPCE et la loi Informatique et Libertés. Un projet de règlement ePrivacy est en discussion depuis 2017 mais reste bloqué au Conseil.",
    context: "La directive ePrivacy a été adoptée en 2002 pour compléter la directive de 1995 sur la protection des données avec des règles spécifiques aux communications électroniques. Elle est la lex specialis du RGPD pour ce secteur. Elle est technologiquement datée mais reste le texte applicable.",
    summary: "La directive ePrivacy régit la vie privée dans les communications électroniques : confidentialité des communications, cookies et technologies de traçage (consentement préalable obligatoire sauf cookies strictement nécessaires), données de trafic et de localisation, et communications commerciales non sollicitées (opt-in pour email/SMS marketing).",
    champ: "Fournisseurs de services de communications électroniques (opérateurs télécoms, FAI). L'article 5§3 (cookies) s'applique à tout éditeur de site web ou d'application mobile. La directive ne couvre pas les services OTT comme WhatsApp.",
    actors: [
      "Opérateurs de communications électroniques (Orange, SFR, Bouygues, Free)",
      "Fournisseurs de services en ligne (pour les cookies — tout site web ou application)",
      "Utilisateurs de services de communications électroniques",
      "CNIL (application en France, notamment pour les cookies)",
    ],
    obligations: [
      "<strong>Confidentialité des communications (art. 5)</strong> — interdiction d'intercepter ou surveiller les communications sans consentement.",
      "<strong>Cookies et traceurs (art. 5§3)</strong> — consentement préalable obligatoire. Exceptions : cookies strictement nécessaires à la fourniture du service.",
      "<strong>Données de trafic (art. 6)</strong> — effacement ou anonymisation à la fin de la communication, sauf pour la facturation.",
      "<strong>Communications non sollicitées (art. 13)</strong> — opt-in obligatoire pour email et SMS marketing. Opt-out pour le démarchage téléphonique (Bloctel en France).",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "En France, la CNIL peut prononcer des amendes jusqu'à 2 % du CA mondial pour les manquements relatifs aux cookies." },
    ],
    articulations: "La directive ePrivacy est la lex specialis du RGPD pour les communications électroniques. Le RGPD s'applique pour le traitement ultérieur des données personnelles collectées via cookies. Le règlement ePrivacy, s'il est adopté, remplacera la directive.",
    timeline: [
      { date: "12 juil. 2002", event: "Adoption de la directive" },
      { date: "2009", event: "Modification : ajout du consentement pour les cookies" },
      { date: "2017", event: "Proposition de règlement ePrivacy par la Commission" },
      { date: "2017–présent", event: "Négociations bloquées au Conseil sur le règlement ePrivacy" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32002L0058",
    updatedAt: "2025-04-29",
  },
];

export function getRegulationById(id: string): RegulationData | undefined {
  return regulationsData.find((r) => r.id === id);
}
