export interface RegulationData {
  id: string;
  badge: string;
  cat: string;
  name: string;
  ref: string;
  type: string;
  status: "active" | "partial" | "upcoming" | "transposed";
  statusLabel: string;
  title: string;
  fullName: string;
  nature: string;
  natureNote: string;
  context: string;
  summary: string;
  champ: string;
  actors: string[];
  obligations: string[];
  sanctions: { amount: string; detail: string }[];
  articulations: string;
  timeline: { date: string; event: string }[];
  link: string;
  updatedAt: string; // ISO date string, e.g. "2025-04-29"
  sanctionsIntro?: string; // Optional intro note displayed above sanctions list
  psNote?: string; // Optional "breaking news" note displayed prominently on the regulation page
}

export const regulationsData: RegulationData[] = [
  {
    id: "rgpd",
    badge: "RGPD",
    cat: "Données",
    name: "Protection des données",
    ref: "Règlement (UE) 2016/679",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "RGPD",
    fullName: "Règlement Général sur la Protection des Données",
    nature: "reglement",
    natureNote: "Le RGPD est un règlement européen : il est d'application directe dans tous les États membres de l'UE depuis le 25 mai 2018. Il ne nécessite pas de loi de transposition. Les États membres conservent néanmoins des marges de manœuvre sur certains points : l'âge du consentement des mineurs (entre 13 et 16 ans selon les pays, 15 ans en France), les traitements dans le cadre de l'emploi, les traitements à des fins journalistiques ou artistiques, et certaines dérogations pour le secteur public. En France, la loi Informatique et Libertés du 6 janvier 1978, modifiée en 2018, complète le RGPD sur ces aspects nationaux.",
    context: "Le RGPD remplace la directive 95/46/CE qui datait de 1995, une époque où internet en était à ses débuts, où les réseaux sociaux n'existaient pas et où le cloud computing n'avait pas de nom. En vingt ans, l'exploitation massive des données personnelles par les géants du numérique (profilage publicitaire, revente de données, surveillance) a rendu ce cadre obsolète. La directive posait un autre problème : en tant que directive, elle avait été transposée de manière hétérogène dans les États membres, créant un patchwork juridique nuisant à la fois aux entreprises (insécurité juridique) et aux citoyens (protections inégales). Le choix du règlement, d'application directe, vise précisément à unifier ce cadre. Le RGPD poursuit trois objectifs principaux :<ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li>renforcer les droits des personnes physiques sur leurs données ;</li><li>responsabiliser les organisations qui les traitent (principe d'accountability) ;</li><li>harmoniser la régulation à l'échelle de l'UE pour créer un marché unique de la donnée fondé sur la confiance.</li></ul>",
    summary: "Le RGPD encadre la collecte, le traitement et la circulation des données à caractère personnel des personnes situées dans l'Union européenne. Il constitue le texte socle de la protection des données en Europe et a une portée extraterritoriale : il s'applique à toute organisation dans le monde qui traite des données de personnes situées dans l'UE. Le règlement repose sur sept principes fondamentaux (licéité, limitation des finalités, minimisation, exactitude, limitation de conservation, intégrité/confidentialité, responsabilité) et six bases légales possibles pour traiter des données (consentement, contrat, obligation légale, intérêts vitaux, mission d'intérêt public, intérêt légitime). Il consacre des droits renforcés pour les personnes (accès, rectification, effacement, portabilité, opposition, limitation) et impose aux responsables de traitement des obligations structurantes : registre des traitements, analyses d'impact, notification des violations dans les 72 heures, privacy by design et by default, et désignation d'un DPO dans certains cas.",
    champ: "Sur le plan matériel, le RGPD couvre tout traitement de données à caractère personnel, automatisé ou non (y compris les fichiers papier), à l'exception des activités purement personnelles ou domestiques, de la politique étrangère et de sécurité commune de l'UE, et des traitements par les autorités à des fins de prévention et détection des infractions pénales (couverts par la directive « Police-Justice » 2016/680).<br><br>Sur le plan territorial (article 3), il s'applique aux organisations établies dans l'UE quel que soit le lieu du traitement, et aux organisations hors UE qui ciblent des personnes dans l'UE (offre de biens/services ou suivi du comportement).",
    actors: [
      "Responsables de traitement (toute entité déterminant les finalités et moyens du traitement)",
      "Sous-traitants (entités traitant des données pour le compte du responsable)",
      "Délégué à la protection des données (DPO)",
      "CNIL (autorité de contrôle française)",
      "Comité européen de la protection des données (CEPD/EDPB)",
      "Personnes concernées (toute personne physique dont les données sont traitées)",
    ],
    obligations: [
      "<strong>Registre des activités de traitement (art. 30)</strong> : obligatoire pour les organisations de plus de 250 salariés, ou en dessous si le traitement présente un risque, concerne des données sensibles ou est régulier.",
      "<strong>Analyse d'impact (AIPD/DPIA, art. 35)</strong> : obligatoire lorsque le traitement est susceptible d'engendrer un risque élevé pour les droits et libertés : profilage systématique, surveillance à grande échelle, données sensibles à grande échelle.",
      "<strong>Privacy by design et by default (art. 25)</strong> : la protection des données doit être intégrée dès la conception du système et par défaut (seules les données nécessaires sont collectées, durée de conservation minimale, accès restreint).",
      "<strong>Notification des violations (art. 33-34)</strong> : notification à l'autorité de contrôle dans les 72 heures suivant la découverte d'une violation. Information des personnes concernées si le risque est élevé.",
      "<strong>Désignation d'un DPO (art. 37-39)</strong> : obligatoire pour les autorités publiques, les organisations dont l'activité implique un suivi régulier et systématique à grande échelle, ou le traitement de données sensibles à grande échelle.",
      "<strong>Encadrement des transferts hors UE (chapitre V)</strong> : les transferts vers des pays tiers ne sont autorisés que sous conditions : décision d'adéquation, clauses contractuelles types (CCT), règles d'entreprise contraignantes (BCR).",
      "<strong>Droits des personnes (chapitre III)</strong> : le RGPD consacre les droits suivants :<ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li>Droit d'accès (art. 15)</li><li>Droit de rectification (art. 16)</li><li>Droit à l'effacement (art. 17)</li><li>Droit à la limitation du traitement (art. 18)</li><li>Droit à la portabilité des données (art. 20)</li><li>Droit d'opposition (art. 21)</li><li>Droit de ne pas faire l'objet d'une décision entièrement automatisée (art. 22)</li></ul>",
    ],
    sanctionsIntro: "L'article 83 du RGPD dispose que les amendes administratives imposées en cas de manquement doivent être effectives, proportionnées et dissuasives. Elles varient selon la gravité de la violation et sont déterminées au cas par cas par l'autorité de contrôle compétente.",
    sanctions: [
      { amount: "20 M€ ou 4 % du CA mondial", detail: "Pour violation des principes fondamentaux, des droits des personnes ou des règles de transfert (art. 83§5)" },
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour manquement aux obligations du responsable/sous-traitant : registre, DPO, notification, privacy by design (art. 83§4)" },
      { amount: "Sanctions pénales (France)", detail: "L'article 226-16 du Code pénal dispose que le fait de procéder ou de faire procéder à des traitements de données à caractère personnel sans respecter les formalités préalables prévues par la loi est puni de cinq ans d'emprisonnement et de 300 000 € d'amende. Ces sanctions s'appliquent également en cas de collecte frauduleuse, de détournement de finalité et d'entrave aux contrôles de la CNIL." },
      { amount: "Bilan 2025 : sanctions prononcées par la CNIL", detail: "Près de 487 millions d'euros d'amendes sur 259 décisions au total, dont 83 sanctions, 143 mises en demeure, 31 rappels aux obligations légales et 2 avertissements. Principales amendes : Google 325 M€, Shein 150 M€, Free 42 M€, France Travail 5 M€." },
    ],
    articulations: "Le RGPD est le texte socle : presque tous les autres textes de droit du numérique européen interagissent avec lui. La directive ePrivacy est sa lex specialis pour les communications électroniques (cookies). Le DSA s'articule avec le RGPD pour la modération de contenu et la publicité ciblée. L'AI Act renvoie au RGPD pour le traitement des données d'entraînement. Le Data Act et le DGA organisent le partage des données tout en renvoyant au RGPD dès que des données personnelles sont concernées.",
    timeline: [
      { date: "27 avril 2016", event: "Adoption du règlement par le Parlement européen et le Conseil" },
      { date: "25 mai 2018", event: "Entrée en application dans tous les États membres" },
      { date: "Juil. 2020", event: "Arrêt Schrems II (CJUE) : invalidation du Privacy Shield UE–États-Unis" },
      { date: "Juil. 2023", event: "Adoption du Data Privacy Framework UE–États-Unis" },
      { date: "2025", event: "Près de 487 M€ d'amendes prononcées par la CNIL sur 259 décisions, un montant record" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32016R0679",
    updatedAt: "2025-04-29",
  },
  {
    id: "dga",
    badge: "DGA",
    cat: "Données",
    name: "Gouvernance des données",
    ref: "Règlement (UE) 2022/868",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DGA",
    fullName: "Data Governance Act — Règlement sur la gouvernance européenne des données",
    nature: "reglement",
    natureNote: "Le DGA est un règlement européen d'application directe dans tous les États membres depuis le 24 septembre 2023. Aucune transposition nationale n'est nécessaire. Les États membres doivent cependant désigner les organismes compétents pour la mise en œuvre.",
    context: "L'Union européenne a constaté que d'immenses volumes de données détenues par le secteur public ou générées par les citoyens et entreprises restaient sous-exploités, faute de mécanismes de confiance permettant leur partage. Le DGA s'inscrit dans la stratégie européenne des données de 2020, aux côtés du Data Act. Son objectif est de créer les conditions de confiance nécessaires au partage volontaire de données entre organisations, sans remettre en cause la protection des données personnelles (RGPD).",
    summary: "Le Data Governance Act établit un cadre de gouvernance pour faciliter le partage et la réutilisation des données au sein de l'UE. Il encadre les conditions de réutilisation des données protégées du secteur public, crée un régime de notification pour les services d'intermédiation de données (data marketplaces), et crée un statut juridique pour les organisations d'altruisme en matière de données : des structures permettant à des citoyens ou des entreprises de partager volontairement leurs données au profit de l'intérêt général (recherche médicale, lutte contre le changement climatique, etc.).",
    champ: "Il s'applique aux organismes du secteur public détenant des données protégées, aux fournisseurs de services d'intermédiation de données, aux organisations d'altruisme en matière de données, et aux utilisateurs de ces services dans l'ensemble de l'UE.",
    actors: [
      "Organismes du secteur public détenant des données protégées",
      "Services d'intermédiation de données (data marketplaces, data trusts)",
      "Organisations d'altruisme en matière de données",
      "Comité européen de l'innovation dans le domaine des données (EDIB)",
      "Autorités compétentes nationales désignées par chaque État membre",
    ],
    obligations: [
      "<strong>Réutilisation des données du secteur public (chapitre II)</strong> : les organismes publics qui autorisent la réutilisation de données protégées doivent le faire dans des conditions non discriminatoires, transparentes et proportionnées. Les exclusivités de réutilisation sont limitées à 12 mois.",
      "<strong>Services d'intermédiation de données (chapitre III)</strong> : les prestataires souhaitant offrir des services d'intermédiation (data marketplaces, data trusts) doivent notifier leur activité à l'autorité compétente nationale. Ils doivent rester neutres vis-à-vis des données qu'ils traitent et garantir la sécurité et l'interopérabilité des échanges.",
      "<strong>Altruisme en matière de données (chapitre IV)</strong> : les organisations collectant des données à des fins d'intérêt général peuvent s'enregistrer comme « organisations d'altruisme en matière de données reconnues dans l'UE ». Depuis mai 2024, la CNIL est l'autorité compétente en France en matière d'altruisme des données. Cette mission consiste à réguler la manière dont des organismes partagent volontairement des données qu'ils estiment utiles pour l'intérêt général — recherche médicale, lutte contre le changement climatique, amélioration des transports publics, etc.",
    ],
    sanctionsIntro: "Le DGA ne fixe pas lui-même le montant des sanctions : il renvoie aux États membres le soin de définir les régimes applicables, tout en encadrant leur liberté (les sanctions doivent être effectives, proportionnées et dissuasives). Les États membres disposent donc d'une marge d'appréciation significative dans la mise en œuvre.",
    sanctions: [
      { amount: "Définies par les États membres", detail: "Les États membres fixent librement les sanctions applicables aux violations du DGA, dans le respect du principe d'effectivité, de proportionnalité et de dissuasion. Aucun plafond harmonisé n'est prévu au niveau européen." },
    ],
    articulations: "Le DGA est complémentaire du Data Act : le DGA crée les mécanismes de gouvernance et de confiance, tandis que le Data Act crée les obligations de partage. Le RGPD s'applique pleinement dès que des données personnelles sont concernées.",
    timeline: [
      { date: "30 mai 2022", event: "Adoption du règlement" },
      { date: "23 juin 2022", event: "Publication au Journal officiel" },
      { date: "24 sept. 2023", event: "Entrée en application" },
      { date: "2024–2026", event: "Mise en place progressive des espaces européens de données sectoriels" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R0868",
    updatedAt: "2025-04-29",
  },
  {
    id: "dataact",
    badge: "Data Act",
    cat: "Données",
    name: "Accès et partage des données",
    ref: "Règlement (UE) 2023/2854",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "Data Act",
    fullName: "Data Act — Règlement sur des règles harmonisées portant sur l'équité de l'accès aux données",
    nature: "reglement",
    natureNote: "Le Data Act est un règlement européen d'application directe. Il est entré en vigueur le 11 janvier 2024 et sera pleinement applicable à partir du 12 septembre 2025. Aucune transposition nationale n'est nécessaire.",
    context: "80 % des données industrielles générées dans l'UE ne sont jamais réutilisées. Les fabricants d'objets connectés conservent un accès exclusif aux données générées par leurs produits, empêchant les utilisateurs et les tiers d'y accéder. Le Data Act vise à corriger ce déséquilibre en créant un droit d'accès aux données pour les utilisateurs de produits connectés.",
    summary: "Le Data Act établit des règles harmonisées sur l'accès aux données générées par les produits connectés (IoT) et les services associés. Il crée un droit pour les utilisateurs d'accéder aux données générées par leurs appareils connectés et de les partager avec des tiers. Le règlement facilite également le changement de fournisseur de services cloud en imposant des obligations de portabilité.",
    champ: "Il s'applique aux fabricants de produits connectés (IoT) et aux fournisseurs de services associés, dès lors que leurs produits ou services sont mis sur le marché de l'UE. Sont visés notamment : les voitures connectées, les montres et bracelets de santé, les thermostats intelligents, les machines industrielles à capteurs, les téléviseurs connectés et les réfrigérateurs connectés. Sont également concernés les utilisateurs de ces produits, les destinataires de données, les fournisseurs de services de traitement de données (cloud, edge, SaaS), ainsi que les organismes du secteur public pouvant demander l'accès à des données privées en cas de nécessité exceptionnelle.",
    actors: [
      "Fabricants de produits connectés (IoT)",
      "Fournisseurs de services liés à un produit connecté",
      "Utilisateurs de produits connectés",
      "Fournisseurs de services cloud, edge et SaaS",
      "Organismes du secteur public",
    ],
    obligations: [
      "<strong>Accès aux données IoT (chapitre II, art. 3-7)</strong> : les fabricants doivent concevoir leurs produits connectés de sorte que les données générées soient accessibles à l'utilisateur, facilement, gratuitement et dans un format structuré et lisible par machine. Cette obligation s'applique aux objets connectés de toutes natures : voitures connectées, montres de santé, thermostats intelligents, machines industrielles, bulldozers, réfrigérateurs connectés, etc.",
      "<strong>Obligations B2B — conditions FRAND (chapitre III)</strong> : lorsqu'un détenteur de données partage des données avec un tiers à des fins commerciales, ce partage doit se faire selon des conditions FRAND — c'est-à-dire équitables, raisonnables et non discriminatoires (de l'anglais : Fair, Reasonable And Non-Discriminatory). Il ne s'agit pas d'une « licence FRAND » mais bien de <em>conditions</em> contractuelles : le terme désigne un ensemble de critères d'équité applicables à la négociation. Les PME bénéficient d'un accès aux données sans frais. Les clauses contractuelles abusives imposées unilatéralement sont nulles de plein droit.",
      "<strong>Accès du secteur public (chapitre V)</strong> : en cas de nécessité exceptionnelle (urgence publique, catastrophe naturelle, pandémie), les organismes publics peuvent demander l'accès à des données détenues par des acteurs privés. Cet accès est temporaire, ciblé et soumis à des garanties strictes.",
      "<strong>Changement de fournisseur cloud (chapitre VI)</strong> : suppression progressive des frais de transfert de données (switching fees), garantie d'interopérabilité et de portabilité des données pour permettre aux utilisateurs de changer de fournisseur de services cloud sans être enfermés dans un écosystème propriétaire.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Le règlement renvoie aux États membres. Les clauses contractuelles abusives sont nulles de plein droit." },
    ],
    articulations: "Le Data Act est complémentaire du DGA : le DGA crée les structures de gouvernance, le Data Act crée les obligations de partage. Le RGPD prévaut dès que des données personnelles sont en jeu.",
    timeline: [
      { date: "13 déc. 2023", event: "Adoption du règlement" },
      { date: "11 janv. 2024", event: "Entrée en vigueur" },
      { date: "12 sept. 2025", event: "Application de la plupart des dispositions" },
      { date: "12 sept. 2026", event: "Application des obligations de portabilité cloud" },
      { date: "12 sept. 2027", event: "Application des exigences d'interopérabilité cloud" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R2854",
    updatedAt: "2025-04-29",
  },
  {
    id: "dsa",
    badge: "DSA",
    cat: "Plateformes",
    name: "Services numériques",
    ref: "Règlement (UE) 2022/2065",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DSA",
    fullName: "Digital Services Act — Règlement sur les services numériques",
    nature: "reglement",
    natureNote: "Le DSA est un règlement européen d'application directe dans tous les États membres depuis le 17 février 2024. Chaque État membre doit désigner un Coordinateur des services numériques (CSN). En France, c'est l'Arcom.",
    context: "Le DSA remplace la directive e-commerce de 2000, adoptée à une époque où les plateformes en ligne n'existaient pas sous leur forme actuelle. En vingt ans, les plateformes sont devenues des acteurs systémiques de l'espace public numérique, posant des problèmes de désinformation, de contenus illicites, de manipulation algorithmique et de publicité ciblée opaque.",
    summary: "Le DSA établit un cadre harmonisé pour la responsabilité des services intermédiaires en ligne selon une architecture à plusieurs niveaux : obligations de base pour tous les intermédiaires, renforcées pour les hébergeurs, encore plus pour les plateformes, et maximales pour les très grandes plateformes (VLOP, +45 millions d'utilisateurs/mois dans l'UE).",
    champ: "Il s'applique à tous les services intermédiaires accessibles aux utilisateurs dans l'Union européenne, quel que soit le lieu d'établissement du prestataire. Le règlement adopte une logique proportionnelle : plus la plateforme est grande et influence, plus ses obligations sont étendues. Sont concernés : les Fournisseurs d'Accès à Internet (FAI), les réseaux de diffusion de contenu (CDN — Content Delivery Networks), les hébergeurs, les plateformes en ligne (réseaux sociaux, marchés en ligne, boutiques d'applications), les Très Grandes Plateformes en Ligne (VLOP — Very Large Online Platforms, désignées par la Commission au-delà de 45 millions d'utilisateurs actifs mensuels dans l'UE) et les Très Grands Moteurs de Recherche en Ligne (VLOSE — Very Large Online Search Engines).",
    actors: [
      "Fournisseurs de services intermédiaires (FAI, hébergeurs, CDN)",
      "Plateformes en ligne (réseaux sociaux, marketplaces, app stores)",
      "VLOP désignées : Meta (Facebook, Instagram), TikTok, X, YouTube, Amazon",
      "VLOSE désignés : Google Search, Bing",
      "Coordinateurs des services numériques (Arcom en France)",
      "Commission européenne (supervision directe des VLOP/VLOSE)",
    ],
    obligations: [
      "<strong>Transparence (art. 15, 24)</strong> : tous les intermédiaires, quelle que soit leur taille, doivent publier des rapports annuels de transparence sur leurs pratiques de modération de contenu — nombre de contenus supprimés, motifs, nombre de comptes suspendus, délais de traitement. L'objectif est de rendre lisibles des décisions qui restaient jusqu'ici opaques. <em>Exemple :</em> Meta publie chaque semestre un rapport de transparence DSA détaillant des millions de suppressions de contenus classées par catégorie (discours haineux, désinformation, nudité, etc.).",
      "<strong>Notification et retrait — « Notice and action » (art. 16)</strong> : les hébergeurs et plateformes doivent mettre en place un mécanisme permettant à tout utilisateur de signaler un contenu illicite (contrefaçon, contenu terroriste, image pédopornographique, escroquerie, etc.). La plateforme doit traiter le signalement rapidement, notifier l'auteur du signalement et informer l'auteur du contenu retiré des voies de recours disponibles. <em>Exemple :</em> un utilisateur qui signale une annonce frauduleuse sur une marketplace doit recevoir une réponse et, si le signalement est fondé, voir le contenu retiré avec notification.",
      "<strong>Traçabilité des vendeurs professionnels — KYBC (art. 30)</strong> : les marchés en ligne doivent vérifier l'identité des vendeurs professionnels selon le principe « Know Your Business Customer » — en français, connaître son client professionnel. Sont vérifiés : le nom, l'adresse, les coordonnées, le numéro d'immatriculation au registre du commerce, le numéro de TVA. L'objectif est d'éradiquer les vendeurs anonymes proposant des produits contrefaits ou dangereux. <em>Exemple :</em> Amazon ou Vinted doivent s'assurer qu'un compte vendeur professionnel est bien enregistré et correspond à une entité juridique réelle avant d'autoriser la vente.",
      "<strong>Transparence et encadrement de la publicité ciblée (art. 26-28)</strong> : les plateformes doivent indiquer à chaque utilisateur pourquoi il voit une publicité particulière (quelles données ont été utilisées pour le cibler). Il est interdit de cibler des publicités sur la base de données dites « sensibles » (santé, convictions politiques ou religieuses, orientation sexuelle) ou à destination des mineurs. Les VLOP doivent tenir un registre public de toutes les publicités diffusées. <em>Exemple :</em> Meta ne peut pas utiliser des données de santé issues de Facebook pour cibler des publicités pharmaceutiques, ni diffuser des publicités pour de l'alcool sur un profil identifié comme mineur.",
      "<strong>Systèmes de recommandation (art. 27)</strong> : les VLOP doivent expliquer clairement les critères de leurs algorithmes de recommandation (popularité, historique de navigation, profil comportemental) et proposer à leurs utilisateurs au moins une option permettant de naviguer sans profilage comportemental. <em>Exemple :</em> TikTok doit offrir la possibilité d'accéder à un fil d'actualité basé uniquement sur la popularité des contenus, sans tenir compte de l'historique de visionnage de l'utilisateur.",
      "<strong>Évaluation des risques systémiques (art. 34-35)</strong> : les VLOP et VLOSE doivent conduire chaque année une analyse approfondie des risques systémiques que leur service peut engendrer : désinformation, manipulation des processus électoraux, violences de genre en ligne, atteinte aux droits fondamentaux, effets sur la santé mentale. Ils doivent ensuite adopter des mesures d'atténuation proportionnées à ces risques. <em>Exemple :</em> X (ex-Twitter) a été sommé d'évaluer ses dispositifs anti-désinformation lors des élections européennes de 2024, ce qui a conduit à l'ouverture d'une procédure formelle.",
      "<strong>Accès aux données pour la recherche (art. 40)</strong> : les VLOP et VLOSE doivent donner accès à leurs données aux chercheurs accrédités par les autorités nationales compétentes, afin de permettre une évaluation indépendante et scientifique des risques systémiques de leurs plateformes. <em>Exemple :</em> des chercheurs universitaires peuvent demander à YouTube l'accès à des données agrégées sur les chaînes recommandées par son algorithme afin d'étudier d'éventuels effets de radicalisation.",
      "<strong>Codes de conduite et lignes directrices au titre du DSA</strong> : le DSA encourage l'adoption de codes de conduite sectoriels validés par la Commission, qui permettent aux plateformes signataires de démontrer leur conformité dans des domaines spécifiques :<ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li>En mars 2024, la Commission a publié des lignes directrices sur les mesures d'atténuation des risques pour les processus électoraux.</li><li>En février 2025, un code de bonnes pratiques contre la désinformation a été formellement intégré dans le cadre du DSA. Signé par une quarantaine d'acteurs (Google Search, YouTube, Instagram, Facebook, Bing, LinkedIn, TikTok, acteurs de la publicité, médias, organismes de recherche et société civile), il constitue depuis le 1er juillet 2025 la référence permettant d'évaluer si les signataires respectent le DSA en matière de désinformation. Un centre de transparence public permet à tout citoyen de suivre sa mise en œuvre.</li><li>Un code de conduite contre les discours de haine illégaux en ligne a également été intégré dans la législation européenne.</li><li>Le 14 juillet 2025, la Commission a présenté des lignes directrices sur la protection des mineurs en ligne. Elles précisent les mesures attendues de toutes les plateformes accessibles aux enfants : vérification de l'âge pour certains services, comptes de mineurs privés par défaut (informations masquées pour les inconnus, captures d'écran interdites, ajout à des groupes soumis au consentement), désactivation des notifications nocturnes, de la géolocalisation et du scrolling infini, limitation des contenus addictifs, accès facilité au numéro de signalement 3018.</li><li>Le même jour, la Commission a lancé un prototype d'application européenne de vérification d'âge, testé dans cinq États membres dont la France. Fondé sur un principe de double anonymat et le recours à un tiers de confiance indépendant, il permet à un utilisateur de prouver sa majorité sans transmettre ses données personnelles à la plateforme.</li></ul>",
    ],
    sanctionsIntro: "L'application du DSA repose sur un réseau de <strong>27 coordinateurs nationaux des services numériques (CSN)</strong>, un par État membre. Ces coordinateurs se réunissent au sein du <strong>Comité européen des services numériques</strong>, qui rend des analyses, coordonne des enquêtes conjointes et émet des recommandations pour une application harmonisée du règlement dans l'ensemble de l'UE.<br><br>En France, le rôle de coordinateur est exercé par l'<strong>Arcom</strong> (Autorité de régulation de la communication audiovisuelle et numérique). La <strong>loi SREN du 21 mai 2024</strong> (loi visant à sécuriser et à réguler l'espace numérique) adapte le droit français au DSA : elle renforce les pouvoirs de l'Arcom en matière de contrôle des plateformes, lui confie la supervision de la vérification de l'âge pour l'accès aux contenus pornographiques en ligne (obligatoire en France depuis 2025, sur la base du référentiel technique de l'Arcom publié en octobre 2024), et lui donne les outils pour ordonner le blocage de plateformes non conformes.<br><br>Pour les Très Grandes Plateformes (VLOP) et les Très Grands Moteurs de Recherche (VLOSE), la surveillance est assurée directement par la <strong>Commission européenne</strong>. Des enquêtes formelles ont d'ores et déjà été ouvertes contre X (ex-Twitter), TikTok, Meta et Temu pour manquements présumés à leurs obligations au titre du DSA.",
    sanctions: [
      { amount: "6 % du CA annuel mondial", detail: "Pour les infractions aux obligations du DSA — cette sanction s'applique notamment aux VLOP et VLOSE qui manquent à leurs obligations renforcées (évaluation des risques systémiques, transparence algorithmique, accès aux données pour les chercheurs)." },
      { amount: "1 % du CA annuel mondial", detail: "Pour fourniture d'informations incorrectes, incomplètes ou trompeuses aux autorités, ou refus de se soumettre à une inspection." },
      { amount: "5 % du CA journalier mondial", detail: "Astreintes journalières en cas de non-conformité persistante malgré une injonction." },
      { amount: "Suspension du service", detail: "En cas de violations graves et répétées constituant un risque grave, la Commission peut ordonner aux VLOP/VLOSE de suspendre temporairement l'accès à leur service dans l'UE (art. 52)." },
    ],
    articulations: "Le DSA coexiste avec le DMA : le DSA régule la responsabilité des plateformes sur les contenus, le DMA régule la contestabilité des marchés numériques. Le RGPD s'applique pour tout ce qui concerne les données personnelles dans la modération et la publicité ciblée. La directive e-commerce de 2000 est partiellement abrogée. En France, la loi SREN du 21 mai 2024 adapte le droit national : elle désigne l'Arcom comme coordinateur des services numériques, étend ses pouvoirs de contrôle et transpose les obligations de coopération avec la Commission européenne.",
    timeline: [
      { date: "19 oct. 2022", event: "Entrée en vigueur du règlement" },
      { date: "25 août 2023", event: "Application aux VLOP et VLOSE désignés" },
      { date: "17 fév. 2024", event: "Application à tous les fournisseurs de services intermédiaires" },
      { date: "21 mai 2024", event: "Adoption de la loi SREN en France — désignation de l'Arcom comme coordinateur national, vérification d'âge pour les sites pornographiques" },
      { date: "2024–2026", event: "Premières procédures formelles de la Commission : X/Twitter, TikTok, Meta, Temu" },
      { date: "1er juil. 2025", event: "Le code de conduite contre la désinformation devient référence d'évaluation au titre du DSA" },
      { date: "14 juil. 2025", event: "Lignes directrices sur la protection des mineurs en ligne + lancement du prototype d'application européenne de vérification d'âge" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2065",
    updatedAt: "2026-05-08",
  },
  {
    id: "dma",
    badge: "DMA",
    cat: "Plateformes",
    name: "Marchés numériques",
    ref: "Règlement (UE) 2022/1925",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DMA",
    fullName: "Digital Markets Act — Règlement sur les marchés numériques",
    nature: "reglement",
    natureNote: "Le DMA est un règlement européen d'application directe depuis le 2 mai 2023. Son application est centralisée : la Commission européenne est seule compétente pour désigner les contrôleurs d'accès et assurer l'application.",
    context: "Les plus grandes plateformes numériques (GAFAM) occupent des positions de contrôle d'accès (gatekeeper) sur des marchés clés : systèmes d'exploitation, navigateurs, app stores, moteurs de recherche, réseaux sociaux. Le droit de la concurrence classique s'est révélé trop lent. Le DMA adopte une approche ex ante : il impose directement des obligations aux contrôleurs d'accès désignés.",
    summary: "Le DMA vise à garantir la contestabilité et l'équité des marchés numériques en imposant des obligations ex ante aux contrôleurs d'accès (gatekeepers). Un gatekeeper fournit un service de plateforme essentiel avec un impact significatif sur le marché intérieur (CA ≥ 7,5 Mds€ ou capitalisation ≥ 75 Mds€) et une position durable (≥ 45 millions d'utilisateurs/mois dans l'UE).",
    champ: "Il s'applique aux entreprises désignées comme contrôleurs d'accès (gatekeepers) par la Commission européenne. Pour être désigné, une entreprise doit réunir trois conditions : exploiter un service de plateforme essentiel (moteur de recherche, réseau social, boutique d'applications, navigateur, système d'exploitation, messagerie, service publicitaire, assistant virtuel ou télévision connectée) ; avoir un impact significatif sur le marché intérieur européen (chiffre d'affaires annuel dans l'UE ≥ 7,5 milliards d'euros ou capitalisation boursière ≥ 75 milliards d'euros) ; et occuper une position durable de contrôle d'accès (≥ 45 millions d'utilisateurs actifs mensuels dans l'UE et ≥ 10 000 entreprises utilisatrices actives par an). En septembre 2023, six entreprises ont été désignées : Alphabet (Google), Amazon, Apple, ByteDance (TikTok), Meta et Microsoft, exploitant au total 22 services de plateforme essentiels.",
    actors: [
      "Contrôleurs d'accès désignés (Alphabet, Amazon, Apple, ByteDance, Meta, Microsoft)",
      "Entreprises utilisatrices des services de plateforme essentielle",
      "Utilisateurs finaux",
      "Commission européenne (application exclusive)",
      "Autorités nationales de concurrence (rôle de soutien)",
    ],
    obligations: [
      "<strong>Interdiction d'auto-préférence (art. 6§5)</strong> : un contrôleur d'accès ne peut pas favoriser ses propres produits ou services dans ses classements au détriment de ceux proposés par des tiers. <em>Exemple :</em> Google ne peut pas faire apparaître Google Shopping ou Google Maps systématiquement en tête des résultats de recherche au détriment de comparateurs concurrents comme Trivago ou PriceComparison.",
      "<strong>Interopérabilité des messageries (art. 7)</strong> : les services de messagerie des contrôleurs d'accès doivent permettre l'interopérabilité avec des services tiers, afin que les utilisateurs ne soient pas enfermés dans un écosystème fermé. <em>Exemple :</em> Meta doit permettre à un utilisateur de WhatsApp de recevoir un message envoyé par un utilisateur de Signal ou Telegram, sans que les deux correspondants aient besoin d'utiliser la même application.",
      "<strong>Liberté de désinstallation et de choix par défaut (art. 6§3-4)</strong> : les utilisateurs doivent pouvoir désinstaller les applications préinstallées et modifier librement les paramètres par défaut de leur appareil (navigateur, moteur de recherche, assistant vocal). <em>Exemple :</em> Apple doit permettre aux utilisateurs d'iPhone de choisir un autre navigateur que Safari comme navigateur par défaut, et de désinstaller des applications préinstallées comme Plans ou Bourse.",
      "<strong>Interdiction du couplage de données entre services (art. 5§2)</strong> : un contrôleur d'accès ne peut pas combiner les données personnelles collectées sur différents services sans avoir obtenu le consentement explicite de l'utilisateur. <em>Exemple :</em> Meta ne peut pas croiser automatiquement les données de Facebook, d'Instagram et de WhatsApp pour construire un profil publicitaire unifié, sans que l'utilisateur ait donné son accord éclairé pour chacun de ces croisements.",
      "<strong>Conditions équitables pour les boutiques d'applications — sideloading (art. 5§4)</strong> : les contrôleurs d'accès doivent autoriser les développeurs à distribuer leurs applications via des canaux autres que la boutique officielle, et ne peuvent pas les contraindre à utiliser leur système de paiement intégré. <em>Exemple :</em> Apple doit permettre l'installation d'applications iOS provenant de boutiques alternatives à l'App Store (sideloading), et ne peut plus imposer sa commission de 30 % sur toutes les transactions réalisées dans les applications.",
      "<strong>Portabilité des données et accès pour les utilisateurs (art. 6§9-10)</strong> : les utilisateurs doivent pouvoir accéder aux données que la plateforme a collectées à leur sujet et les transférer vers un autre service de manière simple et gratuite. <em>Exemple :</em> Google doit permettre à un utilisateur d'exporter l'intégralité de ses photos Google Photos vers un autre service de stockage (Apple Photos, Dropbox) sans frais ni obstacle technique.",
    ],
    sanctionsIntro: "L'application du DMA est centralisée et confiée exclusivement à la Commission européenne — aucun État membre ne peut sanctionner un contrôleur d'accès au titre du DMA. Le 23 avril 2025, la Commission a prononcé ses premières sanctions financières : Apple a été condamné à une amende de 500 millions d'euros pour non-respect des obligations liées à la distribution d'applications alternatives sur l'App Store, et Meta à une amende de 200 millions d'euros pour son système de consentement dit « pay or okay » jugé contraire à l'interdiction du couplage de données. Les deux entreprises risquaient également des astreintes journalières si elles ne se mettaient pas en conformité dans les 60 jours suivant la décision.",
    sanctions: [
      { amount: "10 % du CA mondial", detail: "Pour non-respect des obligations ou des interdictions du DMA. Exemple : Apple (500 M€) et Meta (200 M€) sanctionnés en avril 2025 pour manquements à leurs obligations." },
      { amount: "20 % du CA mondial", detail: "En cas de récidive ou d'infraction systématique : le contrôleur d'accès a déjà fait l'objet d'une décision de non-conformité dans les huit années précédentes." },
      { amount: "5 % du CA journalier mondial", detail: "Astreintes journalières en cas de non-conformité persistante après injonction, pour contraindre la mise en conformité dans les délais impartis." },
      { amount: "Remèdes structurels (art. 18)", detail: "En cas de non-conformité systématique avérée, la Commission peut imposer des remèdes comportementaux ou structurels, y compris la cession d'une partie des activités de l'entreprise." },
    ],
    articulations: "Le DMA est complémentaire du DSA : le DMA régule la concurrence et la contestabilité des marchés, le DSA régule la responsabilité des plateformes sur les contenus. Le règlement P2B (2019/1150) est le précurseur direct du DMA, qui va beaucoup plus loin pour les contrôleurs d'accès. Le DMA interagit avec le RGPD pour les questions de couplage de données. En France, la loi SREN du 21 mai 2024 confie à la Direction générale de la concurrence, de la consommation et de la répression des fraudes (DGCCRF) et à l'Arcom des missions de coopération avec la Commission européenne dans le suivi de la conformité des contrôleurs d'accès.",
    timeline: [
      { date: "1er nov. 2022", event: "Entrée en vigueur du règlement" },
      { date: "2 mai 2023", event: "Début de l'application" },
      { date: "6 sept. 2023", event: "Désignation des 6 premiers contrôleurs d'accès (Alphabet, Amazon, Apple, ByteDance, Meta, Microsoft)" },
      { date: "6 mars 2024", event: "Date limite de mise en conformité pour les contrôleurs d'accès désignés" },
      { date: "21 mai 2024", event: "Adoption de la loi SREN en France — articulation avec le DMA et renforcement des pouvoirs de la DGCCRF et de l'Arcom" },
      { date: "23 avr. 2025", event: "Premières sanctions DMA : Apple condamné à 500 M€, Meta à 200 M€ pour non-conformité" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R1925",
    updatedAt: "2026-05-08",
  },
  {
    id: "p2b",
    badge: "P2B",
    cat: "Plateformes",
    name: "Relations plateformes–entreprises",
    ref: "Règlement (UE) 2019/1150",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "P2B",
    fullName: "Platform-to-Business — Règlement promouvant l'équité et la transparence pour les entreprises",
    nature: "reglement",
    natureNote: "Le P2B est un règlement européen d'application directe depuis le 12 juillet 2020. Il a été en partie supplanté par le DMA pour les plus grandes plateformes, mais reste applicable à toutes les plateformes d'intermédiation.",
    context: "Les PME et commerçants qui vendent via des plateformes (Amazon, Booking, App Store) se trouvent dans une situation de dépendance économique : conditions générales modifiées unilatéralement, déréférencement sans préavis, manque de transparence sur les classements. Le P2B a été le premier texte européen à s'attaquer à ce déséquilibre.",
    summary: "Le règlement P2B impose des obligations de transparence et d'équité aux plateformes d'intermédiation dans leurs relations avec les entreprises utilisatrices. Les plateformes doivent rédiger des conditions claires, notifier à l'avance toute modification, expliquer les raisons de toute restriction, décrire les paramètres de classement, et déclarer tout traitement différencié de leurs propres offres.",
    champ: "Il s'applique aux plateformes d'intermédiation en ligne (marchés en ligne, boutiques d'applications, plateformes de réservation, comparateurs de prix) et aux moteurs de recherche en ligne, dès lors qu'ils mettent en relation des entreprises utilisatrices avec des consommateurs situés dans l'Union européenne. Le règlement s'applique quelle que soit la taille de la plateforme, ce qui le distingue du DMA, réservé aux très grandes plateformes.",
    actors: [
      "Plateformes d'intermédiation en ligne (Amazon, Booking, Uber Eats, Google Play, App Store)",
      "Moteurs de recherche en ligne",
      "Entreprises utilisatrices (vendeurs, développeurs, hôteliers)",
      "Organisations représentatives et associations professionnelles",
    ],
    obligations: [
      "<strong>Conditions générales claires et préavis de modification (art. 3)</strong> : les plateformes doivent rédiger des conditions générales d'utilisation (CGU) rédigées en termes clairs et compréhensibles, facilement accessibles. Toute modification des CGU doit être notifiée aux entreprises utilisatrices avec un préavis d'au moins 15 jours avant son entrée en vigueur. <em>Exemple :</em> si Amazon Marketplace décide de modifier ses règles de commission ou ses politiques de retour pour les vendeurs tiers, elle doit leur envoyer une notification 15 jours avant que les nouvelles conditions entrent en vigueur — les vendeurs peuvent ainsi décider s'ils souhaitent continuer à utiliser la plateforme ou non.",
      "<strong>Motivation obligatoire des restrictions et suspensions (art. 4)</strong> : toute décision de restreindre, suspendre ou résilier l'accès d'une entreprise utilisatrice doit être motivée. La plateforme doit fournir une explication des raisons concrètes qui justifient sa décision, avant ou au moment de la prise d'effet. <em>Exemple :</em> Booking.com ne peut pas déréférencer un hôtel sans expliquer précisément la raison : taux d'annulation trop élevé, violation des CGU, mauvaises évaluations. L'hôtel dispose ainsi des éléments nécessaires pour contester la décision ou se corriger.",
      "<strong>Transparence des paramètres de classement (art. 5)</strong> : les plateformes doivent décrire dans leurs CGU les principaux critères qui déterminent le classement des offres dans les résultats de recherche ou les recommandations, et expliquer leur importance relative. Elles doivent également indiquer si un paiement peut influencer le classement. <em>Exemple :</em> Google Play doit expliquer aux développeurs d'applications si le nombre de téléchargements, la note moyenne des utilisateurs ou un budget publicitaire influencent la position d'une application dans les résultats de recherche de la boutique.",
      "<strong>Déclaration du traitement différencié (art. 7)</strong> : lorsqu'une plateforme propose ses propres produits ou services en concurrence avec ceux des entreprises utilisatrices, elle doit décrire tout traitement différencié qu'elle s'accorde, que ce soit en termes de classement, d'accès aux données ou de conditions techniques. <em>Exemple :</em> Amazon doit déclarer si les produits de sa propre marque « Amazon Basics » bénéficient d'une meilleure mise en avant dans les résultats de recherche que les produits de vendeurs tiers comparables.",
      "<strong>Mécanisme interne de traitement des réclamations (art. 11)</strong> : les plateformes d'une certaine taille doivent mettre en place un système interne gratuit permettant aux entreprises utilisatrices de déposer des réclamations. La plateforme doit traiter ces réclamations rapidement et de manière transparente. <em>Exemple :</em> un vendeur dont le compte a été suspendu sur Zalando doit avoir accès à un mécanisme d'appel interne lui permettant de contester la décision et d'obtenir une réponse motivée dans un délai raisonnable.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Le P2B ne fixe pas lui-même les sanctions : il renvoie aux États membres le soin de définir des régimes effectifs, proportionnés et dissuasifs. Pour les très grandes plateformes, le DMA a pris le relais avec des sanctions beaucoup plus lourdes (jusqu'à 10 % du chiffre d'affaires mondial)." },
    ],
    articulations: "Le P2B est le précurseur direct du DMA, qui va beaucoup plus loin pour les contrôleurs d'accès désignés. Le P2B reste pleinement applicable à toutes les plateformes qui ne relèvent pas du DMA, c'est-à-dire la grande majorité des plateformes de taille moyenne. Le DMA et le P2B se complètent : le P2B protège les entreprises utilisatrices de toutes les plateformes, tandis que le DMA impose des obligations structurelles aux seuls gatekeepers.",
    timeline: [
      { date: "20 juin 2019", event: "Adoption du règlement" },
      { date: "12 juil. 2020", event: "Entrée en application" },
      { date: "2022", event: "Adoption du DMA, qui va plus loin pour les gatekeepers" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019R1150",
    updatedAt: "2025-04-29",
  },
  {
    id: "nis2",
    badge: "NIS 2",
    cat: "Cybersécurité",
    name: "Sécurité des réseaux et systèmes",
    ref: "Directive (UE) 2022/2555",
    type: "Directive",
    status: "partial",
    statusLabel: "Transposition en cours",
    title: "NIS 2",
    fullName: "Directive sur un niveau élevé commun de cybersécurité dans l'Union",
    nature: "directive",
    natureNote: "Étant une directive, NIS2 nécessite une loi de transposition. Le délai de transposition avait été fixé au 17 octobre 2024. En France, le projet de loi « Résilience » a été adopté par le Sénat le 12 mars 2025 mais le vote à l'Assemblée nationale est reporté à juillet 2026. La Commission a envoyé un avis motivé à la France en mai 2025.",
    context: "La directive NIS 1 de 2016 avait un périmètre très restreint (environ 300 entités en France) et une application hétérogène. Face à l'augmentation massive des cyberattaques, l'UE a décidé de remplacer NIS 1 par un cadre beaucoup plus ambitieux. NIS 2 multiplie par 50 le nombre d'entités concernées en France (de 300 à 15 000-18 000).",
    summary: "La directive NIS 2 renforce le cadre de cybersécurité européen en élargissant son champ à 18 secteurs (contre 7 pour NIS 1), en introduisant des obligations de gestion des risques plus strictes, et en responsabilisant personnellement les dirigeants. Elle crée deux catégories : entités essentielles (EE) et entités importantes (EI), soumises à des régimes de supervision différenciés.",
    champ: "Il s'applique aux entités de taille moyenne et grande (plus de 50 salariés ou chiffre d'affaires/bilan annuel supérieur à 10 millions d'euros) opérant dans 18 secteurs répartis en deux catégories. Les <strong>entités essentielles (EE)</strong>, soumises aux obligations les plus strictes, couvrent : l'énergie, les transports, le secteur bancaire, les infrastructures des marchés financiers, la santé, l'eau potable, les eaux usées, les infrastructures numériques, la gestion des services TIC, les administrations publiques et l'espace. Les <strong>entités importantes (EI)</strong> couvrent : les services postaux et de livraison, la gestion des déchets, la fabrication et distribution de produits chimiques, la production alimentaire, la fabrication industrielle (dispositifs médicaux, électronique, machines, véhicules), les fournisseurs de services numériques et les organismes de recherche.",
    actors: [
      "Entités essentielles (EE) et entités importantes (EI) dans les 18 secteurs couverts",
      "ANSSI (autorité nationale compétente en France)",
      "CSIRT nationaux (centres de réponse aux incidents)",
      "Réseau CyCLONe (coordination des crises cyber au niveau européen)",
      "ENISA (Agence de l'UE pour la cybersécurité)",
      "Dirigeants des entités concernées (responsabilité personnelle)",
    ],
    obligations: [
      "<strong>Mesures de gestion des risques (art. 21)</strong> : les entités doivent adopter des mesures techniques et organisationnelles proportionnées pour gérer les risques qui menacent la sécurité de leurs réseaux et systèmes d'information. Cela comprend : l'analyse et la cartographie des risques, la mise en place de l'authentification multifacteur (MFA), le chiffrement des données sensibles, la gestion des accès, les sauvegardes régulières et les plans de continuité d'activité. <em>Exemple :</em> un hôpital (entité essentielle) doit cartographier l'ensemble de ses systèmes informatiques (dossiers patients, équipements médicaux connectés, imagerie), identifier les vulnérabilités et mettre en place des contrôles d'accès stricts pour éviter qu'une attaque par ransomware ne paralyse ses activités, comme cela s'est produit à l'hôpital de Corbeil-Essonnes en 2022.",
      "<strong>Notification des incidents de sécurité (art. 23)</strong> : tout incident ayant un impact significatif sur la continuité des services doit être signalé selon un calendrier précis : alerte initiale dans les 24 heures suivant la découverte, notification complète dans les 72 heures avec une première évaluation de l'incident, puis rapport final dans un délai d'un mois. <em>Exemple :</em> une entreprise de logistique (entité importante) qui découvre une intrusion dans son système de gestion de flotte à 9h doit envoyer une alerte à l'ANSSI au plus tard à 9h le lendemain, même si elle ne connaît pas encore l'étendue complète de l'attaque.",
      "<strong>Responsabilité personnelle des dirigeants (art. 20)</strong> : les organes de direction des entités concernées (conseils d'administration, directoires, comités exécutifs) doivent approuver les mesures de cybersécurité, en assurer la mise en œuvre et suivre des formations régulières. En cas de manquement grave, les dirigeants peuvent être tenus personnellement responsables et faire l'objet d'une interdiction temporaire d'exercer leurs fonctions. <em>Exemple :</em> le directeur général d'un opérateur d'énergie qui ignorerait délibérément les recommandations de son équipe sécurité pourrait être sanctionné personnellement si une cyberattaque survient.",
      "<strong>Enregistrement auprès de l'autorité nationale (art. 3 et 27)</strong> : toutes les entités entrant dans le champ de NIS2 doivent s'enregistrer auprès de l'autorité nationale compétente de leur État membre. En France, cette autorité est l'ANSSI (Agence nationale de la sécurité des systèmes d'information). Cet enregistrement permet à l'autorité de tenir un registre des entités concernées et d'organiser la supervision.",
      "<strong>Sécurité de la chaîne d'approvisionnement (art. 21§2(d))</strong> : les entités doivent évaluer et gérer les risques de cybersécurité liés à leurs fournisseurs et prestataires de services. Une vulnérabilité chez un sous-traitant peut compromettre l'entité principale. <em>Exemple :</em> suite à l'affaire SolarWinds (2020), dans laquelle des pirates ont compromis un logiciel de gestion informatique utilisé par des centaines d'organisations, les entreprises doivent s'assurer que leurs fournisseurs de logiciels et de services cloud appliquent des standards de sécurité équivalents aux leurs.",
    ],
    sanctions: [
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour les entités essentielles" },
      { amount: "7 M€ ou 1,4 % du CA mondial", detail: "Pour les entités importantes" },
      { amount: "Responsabilité personnelle des dirigeants", detail: "Possibilité d'interdictions temporaires d'exercer pour les dirigeants d'entités essentielles" },
    ],
    articulations: "NIS 2 s'articule avec le CRA (exigences de cybersécurité aux produits), le Cybersecurity Act (certification européenne), et DORA, qui constitue la lex specialis pour le secteur financier : les entités financières soumises à DORA sont exemptées de NIS 2.",
    timeline: [
      { date: "14 déc. 2022", event: "Adoption de la directive" },
      { date: "17 oct. 2024", event: "Date limite de transposition (non respectée par la plupart des États membres)" },
      { date: "Mai 2025", event: "Avis motivé de la Commission à 19 États membres dont la France" },
      { date: "17 mars 2026", event: "Publication par l'ANSSI du Référentiel Cyber France (ReCyF)" },
      { date: "Juil. 2026 (prévu)", event: "Vote de la loi de transposition à l'Assemblée nationale" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022L2555",
    updatedAt: "2025-04-29",
  },
  {
    id: "cra",
    badge: "CRA",
    cat: "Cybersécurité",
    name: "Cyber-résilience des produits",
    ref: "Règlement (UE) 2024/2847",
    type: "Règlement",
    status: "upcoming",
    statusLabel: "Application progressive",
    title: "CRA",
    fullName: "Cyber Resilience Act — Exigences de cybersécurité pour les produits numériques",
    nature: "reglement",
    natureNote: "Le CRA est un règlement européen d'application directe. Entré en vigueur le 10 décembre 2024, avec application progressive jusqu'au 11 décembre 2027.",
    context: "Les produits connectés sont mis sur le marché avec des vulnérabilités connues, sans obligation de les corriger après la vente. Aucune réglementation horizontale n'existait pour imposer des exigences de cybersécurité aux fabricants. Le CRA applique au numérique la logique du marquage CE.",
    summary: "Le CRA impose pour la première fois des exigences de cybersécurité obligatoires à tous les produits comportant des éléments numériques mis sur le marché européen. Les fabricants doivent intégrer la sécurité dès la conception (security by design), assurer des mises à jour pendant la durée de vie du produit (minimum 5 ans), et signaler les vulnérabilités activement exploitées à l'ENISA dans les 24 heures.",
    champ: "Tous les produits comportant des éléments numériques : objets connectés (IoT), logiciels, matériel informatique (routeurs, smartphones, ordinateurs). Sont exclus : dispositifs médicaux, aviation, véhicules, produits exclusivement destinés à la défense nationale.",
    actors: [
      "Fabricants de produits comportant des éléments numériques",
      "Importateurs et distributeurs",
      "ENISA (coordination des signalements de vulnérabilités)",
      "Organismes d'évaluation de la conformité (organismes notifiés)",
      "Autorités de surveillance du marché dans chaque État membre",
    ],
    obligations: [
      "<strong>Security by design (annexe I)</strong> — les produits doivent être conçus avec un niveau de cybersécurité approprié : protection contre les accès non autorisés, minimisation des surfaces d'attaque.",
      "<strong>Gestion des vulnérabilités</strong> — identifier et documenter les vulnérabilités, fournir des mises à jour gratuites pendant au moins 5 ans, politique coordonnée de divulgation.",
      "<strong>Signalement (art. 14)</strong> — notification à l'ENISA dans les 24 heures pour une vulnérabilité activement exploitée, notification complète dans les 72 heures.",
      "<strong>Marquage CE</strong> — selon la catégorie du produit, auto-évaluation ou évaluation par un organisme tiers.",
      "<strong>SBOM</strong> — les fabricants doivent établir et maintenir une nomenclature des composants logiciels.",
    ],
    sanctions: [
      { amount: "15 M€ ou 2,5 % du CA mondial", detail: "Pour non-respect des exigences essentielles de cybersécurité" },
      { amount: "10 M€ ou 2 % du CA mondial", detail: "Pour non-respect des autres obligations (signalement, documentation)" },
      { amount: "5 M€ ou 1 % du CA mondial", detail: "Pour fourniture d'informations incorrectes aux autorités" },
    ],
    articulations: "Le CRA complète NIS 2 : NIS 2 impose des obligations aux entités (organisations), le CRA aux produits. Il interagit avec le Cybersecurity Act pour la certification et avec le Data Act pour l'accès aux données des produits connectés.",
    timeline: [
      { date: "12 mars 2024", event: "Adoption par le Parlement européen" },
      { date: "10 déc. 2024", event: "Entrée en vigueur" },
      { date: "11 sept. 2026", event: "Application des obligations de signalement des vulnérabilités" },
      { date: "11 déc. 2027", event: "Application de l'ensemble des obligations (security by design, marquage CE)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R2847",
    updatedAt: "2025-04-29",
  },
  {
    id: "cybersecact",
    badge: "CSA",
    cat: "Cybersécurité",
    name: "Certification de cybersécurité",
    ref: "Règlement (UE) 2019/881",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "Cybersecurity Act",
    fullName: "Cybersecurity Act — Règlement relatif à l'ENISA et à la certification de cybersécurité",
    nature: "reglement",
    natureNote: "Le Cybersecurity Act est un règlement européen d'application directe depuis le 27 juin 2019. Il ne nécessite aucune transposition nationale.",
    context: "Avant le Cybersecurity Act, il n'existait pas de cadre européen unifié pour la certification de cybersécurité. Chaque État membre avait ses propres schémas nationaux (CSPN en France, BSI en Allemagne), créant une fragmentation coûteuse pour les entreprises.",
    summary: "Le Cybersecurity Act renforce le mandat de l'ENISA (qui devient une agence permanente) et crée un cadre européen de certification de cybersécurité volontaire pour les produits, services et processus TIC, avec trois niveaux d'assurance (élémentaire, substantiel, élevé).",
    champ: "Produits, services et processus TIC mis sur le marché de l'UE. Organismes nationaux d'accréditation et d'évaluation de la conformité.",
    actors: [
      "ENISA (rôle central dans la préparation des schémas et la coordination)",
      "Commission européenne (adoption des schémas par actes d'exécution)",
      "Autorités nationales de certification (ANSSI en France)",
      "Organismes d'évaluation de la conformité",
      "Fabricants et fournisseurs de produits/services TIC",
    ],
    obligations: [
      "<strong>Schémas européens de certification (art. 46-65)</strong> — l'ENISA prépare des schémas candidats. Chaque schéma définit les produits/services couverts, les exigences et les méthodes d'évaluation.",
      "<strong>Trois niveaux d'assurance (art. 52)</strong> — élémentaire (auto-évaluation), substantiel (évaluation par tiers), élevé (organisme accrédité avec tests de pénétration).",
      "<strong>Reconnaissance mutuelle (art. 56)</strong> — un certificat délivré dans un État membre est reconnu dans tous les autres.",
      "<strong>ENISA renforcée</strong> — mandat permanent, assistance technique, coordination des incidents à grande échelle.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Sanctions pour utilisation frauduleuse de certificats ou non-respect des obligations de certification." },
    ],
    articulations: "Le Cybersecurity Act fournit le cadre de certification utilisé par NIS 2 et le CRA. Il interagit aussi avec le RGPD pour la certification en matière de protection des données (art. 42 RGPD).",
    timeline: [
      { date: "17 avril 2019", event: "Adoption du règlement" },
      { date: "27 juin 2019", event: "Entrée en vigueur" },
      { date: "2020", event: "Premier schéma de certification adopté : EUCC (critères communs européens)" },
      { date: "2024–2026", event: "Schémas en cours : EUCS (cloud), EU5G (réseaux 5G)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019R0881",
    updatedAt: "2025-04-29",
  },
  {
    id: "aiact",
    badge: "AI Act",
    cat: "IA",
    name: "Intelligence artificielle",
    ref: "Règlement (UE) 2024/1689",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "AI Act",
    fullName: "Règlement établissant des règles harmonisées concernant l'intelligence artificielle",
    nature: "reglement",
    natureNote: "L'AI Act est un règlement européen d'application directe, entré en vigueur le 1er août 2024. Il s'applique de manière progressive depuis février 2025 et devrait s'appliquer entièrement d'ici août 2027. En France, la CNIL, la DGCCRF et l'Arcom se partagent les compétences.",
    context: "L'AI Act est le premier cadre juridique au monde dédié à la régulation de l'intelligence artificielle. Proposé en avril 2021, avant l'explosion de l'IA générative (ChatGPT, fin 2022), il a conduit à des ajouts importants sur les modèles d'IA à usage général (GPAI). Il adopte une approche fondée sur le risque.",
    summary: "L'AI Act encadre le développement, la mise sur le marché et l'utilisation des systèmes d'IA selon quatre niveaux de risque. Les pratiques à risque inacceptable sont interdites. Les systèmes à haut risque (recrutement, crédit, justice, éducation, biométrie) ont des obligations strictes. Les modèles GPAI à risque systémique ont des obligations renforcées.",
    champ: "Il s'applique à tout fournisseur développant ou mettant sur le marché un système d'IA dans l'UE, à tout déployeur professionnel, et à tout fournisseur hors UE dont le système produit des résultats utilisés dans l'UE. Sont exclus : la recherche scientifique sans objectif commercial, les systèmes militaires et les utilisations purement personnelles.",
    actors: [
      "Fournisseurs de systèmes d'IA (développeurs, éditeurs)",
      "Déployeurs (entreprises et organisations utilisant des systèmes d'IA)",
      "Fournisseurs de modèles GPAI (OpenAI, Google, Meta, Mistral, etc.)",
      "Bureau européen de l'IA (AI Office, au sein de la Commission)",
      "Autorités nationales compétentes (CNIL, DGCCRF, Arcom en France)",
    ],
    obligations: [
      "<div style=\"margin:8px 0 12px;\"><p style=\"font-weight:600;margin-bottom:10px;\">Pyramide des risques de l'AI Act :</p><div style=\"display:flex;flex-direction:column;align-items:center;gap:3px;max-width:440px;\"><div style=\"background:#fee2e2;border:1px solid #fca5a5;border-radius:6px;padding:7px 14px;text-align:center;width:38%;font-size:12px;font-weight:600;color:#991b1b;\">🚫 Risque inacceptable<br><span style=\"font-weight:400;font-size:11px;\">Pratiques interdites (art. 5)</span></div><div style=\"background:#ffedd5;border:1px solid #fdba74;border-radius:6px;padding:7px 14px;text-align:center;width:58%;font-size:12px;font-weight:600;color:#9a3412;\">⚠️ Haut risque<br><span style=\"font-weight:400;font-size:11px;\">Obligations strictes (art. 6-51)</span></div><div style=\"background:#fef9c3;border:1px solid #fde047;border-radius:6px;padding:7px 14px;text-align:center;width:78%;font-size:12px;font-weight:600;color:#713f12;\">💬 Risque limité<br><span style=\"font-weight:400;font-size:11px;\">Obligations de transparence (art. 50)</span></div><div style=\"background:#dcfce7;border:1px solid #86efac;border-radius:6px;padding:7px 14px;text-align:center;width:100%;font-size:12px;font-weight:600;color:#14532d;\">✅ Risque minimal<br><span style=\"font-weight:400;font-size:11px;\">Aucune obligation spécifique</span></div></div></div>",
      "<strong>Interdictions (art. 5)</strong> : scoring social par les autorités publiques, manipulation subliminale ou exploitation des vulnérabilités, identification biométrique à distance en temps réel dans l'espace public (sauf exceptions strictes telles que la recherche d'un enfant disparu ou la prévention d'une menace terroriste imminente).",
      "<strong>Systèmes à haut risque (chapitre III)</strong> : gestion des risques, gouvernance des données d'entraînement, documentation technique, journalisation automatique, supervision humaine, exactitude et robustesse, marquage CE, inscription dans la base de données européenne de l'IA.",
      "<strong>Obligations de transparence (art. 50)</strong> : les systèmes d'IA interagissant avec des personnes (chatbots) doivent informer les utilisateurs qu'ils interagissent avec une IA. Par exemple, le chatbot « Amélie » de l'Assurance Maladie doit afficher clairement qu'il s'agit d'un assistant automatisé. Les contenus générés par IA (textes, images, sons) et les deepfakes doivent être étiquetés comme tels.",
      "<strong>Modèles GPAI — General Purpose AI (chapitre V)</strong> : les modèles GPAI sont des modèles d'IA entraînés sur de grandes quantités de données, capables de réaliser de nombreuses tâches différentes (comme les grands modèles de langage GPT, Claude ou Gemini). Leurs obligations comprennent : documentation technique, respect du droit d'auteur, publication d'un résumé des données d'entraînement. Pour les modèles à risque systémique : évaluation des risques, tests adversariaux, signalement des incidents graves à l'AI Office.",
      "<strong>Bacs à sable réglementaires (art. 57)</strong> : un bac à sable réglementaire est un environnement contrôlé et supervisé permettant à des fournisseurs de tester et valider leurs systèmes d'IA avant leur mise sur le marché, sous la surveillance des autorités compétentes. Chaque État membre doit mettre en place au moins un bac à sable réglementaire d'ici le 2 août 2026.",
    ],
    sanctionsIntro: "Les sanctions prévues par l'AI Act varient selon la nature de la non-conformité et la catégorie d'entreprise. Elles sont déterminées soit en pourcentage du chiffre d'affaires annuel mondial, soit sur la base de seuils absolus, en retenant le montant le plus élevé.",
    sanctions: [
      { amount: "35 M€ ou 7 % du CA mondial", detail: "Pour violation des pratiques interdites (art. 5 : notation sociale, manipulation subliminale, identification biométrique non autorisée)" },
      { amount: "15 M€ ou 3 % du CA mondial", detail: "Pour manquement aux exigences applicables aux systèmes à haut risque et aux obligations des fournisseurs, déployeurs et représentants autorisés" },
      { amount: "7,5 M€ ou 1 % du CA mondial", detail: "Pour non-conformité aux exigences de transparence (risque limité) et pour fourniture d'informations incorrectes ou trompeuses aux autorités" },
      { amount: "Sanctions réduites pour PME et start-ups", detail: "Pour les PME et start-ups, les amendes sont plafonnées au montant le plus faible entre le pourcentage du chiffre d'affaires et le seuil absolu, afin de garantir leur proportionnalité et de ne pas entraver l'innovation." },
    ],
    articulations: "L'AI Act s'articule étroitement avec le RGPD pour le traitement des données personnelles dans l'entraînement et le déploiement. Le CRA s'applique aux systèmes d'IA embarqués dans des produits connectés. La directive droit d'auteur (art. 3-4 sur l'exception TDM) est pertinente pour les données d'entraînement.",
    timeline: [
      { date: "13 mars 2024", event: "Adoption par le Parlement européen" },
      { date: "1er août 2024", event: "Entrée en vigueur" },
      { date: "2 fév. 2025", event: "Interdiction des pratiques d'IA à risque inacceptable" },
      { date: "2 août 2025", event: "Obligations pour les modèles GPAI, désignation des autorités nationales" },
      { date: "2 déc. 2026", event: "⚠️ [Accord provisoire] Report de l'obligation de détection et de marquage des contenus générés par IA (art. 50§2)" },
      { date: "2 août 2026", event: "Application complète pour les systèmes à haut risque (annexe III) — date en vigueur aujourd'hui" },
      { date: "2 déc. 2027", event: "⚠️ [Accord provisoire] Nouvelle date d'application pour les systèmes à haut risque (annexe III)" },
      { date: "2 août 2028", event: "⚠️ [Accord provisoire] Nouvelle date d'application pour les systèmes à haut risque (annexe I)" },
    ],
    psNote: "🔴 Accord politique provisoire — mai 2026 : les institutions européennes ont annoncé un accord sur des amendements à l'AI Act. La loi n'est pas encore formellement modifiée, mais plusieurs changements importants sont attendus : <ul style=\"list-style-type:disc;padding-left:1.25rem;margin-top:0.5rem;\"><li><strong>Report des délais d'application pour les systèmes à haut risque</strong> : la date du 2 août 2026 (annexe III) serait repoussée au 2 décembre 2027 ; celle de l'annexe I au 2 août 2028.</li><li><strong>Nouvelles pratiques interdites</strong> : les systèmes d'IA capables de générer des contenus sexuels non consentis ou des contenus pédopornographiques (CSAM) seraient ajoutés à la liste des pratiques interdites (art. 5).</li><li><strong>Report du marquage des contenus génératifs</strong> : l'obligation de détection et de filigranage des sorties IA (art. 50§2) serait repoussée au 2 décembre 2026.</li><li><strong>Traitement des données sensibles pour la détection des biais</strong> : la portée serait élargie pour permettre aux organisations de traiter des données personnelles sensibles dans le cadre de la détection et correction des biais, sous conditions strictes.</li></ul><em>Ces modifications font l'objet d'un accord politique ; elles doivent encore être formellement adoptées avant la date d'applicabilité du 2 août 2026.</em>",
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    updatedAt: "2026-05-08",
  },
  {
    id: "dora",
    badge: "DORA",
    cat: "Finance",
    name: "Résilience opérationnelle numérique",
    ref: "Règlement (UE) 2022/2554",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "DORA",
    fullName: "Digital Operational Resilience Act — Résilience opérationnelle numérique du secteur financier",
    nature: "reglement",
    natureNote: "DORA est un règlement européen d'application directe depuis le 17 janvier 2025. Il est la lex specialis en matière de cybersécurité pour le secteur financier — les entités soumises à DORA sont exemptées de NIS 2.",
    context: "Le secteur financier est l'un des plus exposés aux risques cyber. Les incidents informatiques dans les banques peuvent provoquer des crises systémiques. Avant DORA, les exigences de résilience numérique étaient fragmentées entre diverses directives sectorielles. DORA crée un cadre unique et horizontal.",
    summary: "DORA impose des exigences uniformes de résilience opérationnelle numérique à l'ensemble des entités financières de l'UE. Il couvre cinq piliers : gestion des risques TIC, gestion et signalement des incidents TIC, tests de résilience (dont tests de pénétration avancés TLPT), gestion des risques liés aux prestataires tiers, et partage d'informations sur les cybermenaces.",
    champ: "Plus de 20 types d'entités financières : établissements de crédit, entreprises d'investissement, assurances, fonds de pension, prestataires de services sur crypto-actifs (MiCA), etc. Également les prestataires tiers critiques de services TIC (cloud providers).",
    actors: [
      "Entités financières (banques, assurances, sociétés de gestion, PSP)",
      "Prestataires tiers critiques de services TIC (cloud, SaaS)",
      "Autorités européennes de surveillance (ABE, AEAPP, AEMF)",
      "Autorités nationales de supervision financière (ACPR, AMF en France)",
      "Superviseur principal (Lead Overseer) pour les prestataires tiers critiques",
    ],
    obligations: [
      "<strong>Gestion des risques TIC (chapitre II)</strong> — cadre complet : stratégie de résilience, politiques de sécurité, gestion des actifs TIC, détection des menaces, plans de continuité.",
      "<strong>Signalement des incidents (chapitre III)</strong> — classification selon des critères harmonisés. Signalement des incidents majeurs à l'autorité compétente.",
      "<strong>Tests de résilience (chapitre IV)</strong> — tests réguliers (vulnérabilités, pénétration). Tests de pénétration avancés TLPT tous les 3 ans pour les entités importantes.",
      "<strong>Risques liés aux tiers (chapitre V)</strong> — clauses minimales dans les contrats TIC (accès, audit, sécurité, portabilité). Supervision directe des prestataires critiques.",
    ],
    sanctions: [
      { amount: "Définies par les États membres et les AES", detail: "Selon les cadres sectoriels financiers existants" },
      { amount: "Astreintes pour les prestataires tiers critiques", detail: "1 % du CA mondial quotidien moyen pour les prestataires non conformes" },
    ],
    articulations: "DORA est la lex specialis de NIS 2 pour le secteur financier. Il interagit avec MiCA pour les prestataires de services sur crypto-actifs et avec le RGPD pour la notification des incidents impliquant des données personnelles.",
    timeline: [
      { date: "14 déc. 2022", event: "Adoption du règlement" },
      { date: "16 janv. 2023", event: "Entrée en vigueur" },
      { date: "17 janv. 2025", event: "Application de l'ensemble des dispositions" },
      { date: "2025–2026", event: "Premiers cycles de tests TLPT et désignation des prestataires tiers critiques" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2554",
    updatedAt: "2025-04-29",
  },
  {
    id: "mica",
    badge: "MiCA",
    cat: "Finance",
    name: "Marchés de crypto-actifs",
    ref: "Règlement (UE) 2023/1114",
    type: "Règlement",
    status: "active",
    statusLabel: "En vigueur",
    title: "MiCA",
    fullName: "Markets in Crypto-Assets — Règlement sur les marchés de crypto-actifs",
    nature: "reglement",
    natureNote: "MiCA est un règlement européen d'application directe. Les dispositions sur les stablecoins sont applicables depuis le 30 juin 2024, et l'ensemble du règlement depuis le 30 décembre 2024.",
    context: "Le marché des crypto-actifs s'est développé en marge du cadre réglementaire financier, entraînant des risques importants pour les investisseurs (escroqueries, faillites comme FTX). MiCA est le premier cadre juridique complet au monde pour les crypto-actifs, créant un « passeport européen » pour les prestataires.",
    summary: "MiCA établit un cadre juridique harmonisé pour l'émission et la négociation de crypto-actifs dans l'UE. Il distingue trois catégories : jetons référencés à des actifs (ART — stablecoins), jetons de monnaie électronique (EMT), et autres crypto-actifs. Les prestataires de services (CASP) doivent obtenir un agrément auprès de leur autorité nationale (AMF en France).",
    champ: "Émetteurs de crypto-actifs (ART, EMT, utility tokens), prestataires de services sur crypto-actifs (CASP : plateformes d'échange, services de conservation, conseil). Sont exclus : crypto-actifs qualifiés d'instruments financiers (MiFID II), NFT uniques.",
    actors: [
      "Émetteurs de crypto-actifs (projets blockchain, émetteurs de stablecoins)",
      "Prestataires de services sur crypto-actifs (CASP — Binance, Coinbase, Kraken)",
      "Autorité bancaire européenne (ABE — supervision des ART et EMT significatifs)",
      "Autorités nationales compétentes (AMF en France pour les CASP)",
      "Investisseurs et détenteurs de crypto-actifs",
    ],
    obligations: [
      "<strong>Livre blanc (art. 6, 17, 51)</strong> — tout émetteur doit publier un livre blanc décrivant le projet, les risques et les droits associés.",
      "<strong>Réserve d'actifs pour les ART (art. 36-39)</strong> — maintenir une réserve liquide couvrant 100 % des jetons émis, avec des règles strictes de composition et de transparence.",
      "<strong>Agrément des CASP (art. 59-63)</strong> — obtenir un agrément auprès de l'autorité nationale, valable dans toute l'UE (passeport européen).",
      "<strong>Obligations de conduite (art. 66-82)</strong> — agir loyalement, informer sur les risques, séparer les actifs des clients des actifs propres.",
      "<strong>Prévention des abus de marché (titre VI)</strong> — interdiction des opérations d'initiés, de la manipulation de marché.",
    ],
    sanctions: [
      { amount: "Jusqu'à 5 M€ ou 3-12,5 % du CA", detail: "Selon le type d'infraction et les choix nationaux" },
      { amount: "Retrait d'agrément", detail: "En cas de manquement grave" },
    ],
    articulations: "MiCA s'articule avec DORA pour les exigences de résilience numérique des CASP. Le RGPD s'applique au traitement des données personnelles des clients. La directive anti-blanchiment s'applique pour la lutte contre le blanchiment.",
    timeline: [
      { date: "9 juin 2023", event: "Adoption du règlement" },
      { date: "30 juin 2024", event: "Application des titres III et IV (ART et EMT)" },
      { date: "30 déc. 2024", event: "Application complète (CASP, abus de marché)" },
      { date: "2025–2026", event: "Période transitoire pour les CASP existants (agrément à obtenir)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R1114",
    updatedAt: "2025-04-29",
  },
  {
    id: "eidas2",
    badge: "eIDAS 2",
    cat: "Identité",
    name: "Identité numérique européenne",
    ref: "Règlement (UE) 2024/1183",
    type: "Règlement",
    status: "partial",
    statusLabel: "Application progressive",
    title: "eIDAS 2",
    fullName: "Règlement modifiant eIDAS — Portefeuille européen d'identité numérique (EUDIW)",
    nature: "reglement",
    natureNote: "eIDAS 2 est un règlement européen d'application directe, entré en vigueur le 20 mai 2024. Les États membres doivent mettre à disposition le portefeuille d'identité numérique (EUDIW) d'ici mai 2026.",
    context: "Le règlement eIDAS de 2014 avait créé un cadre pour la reconnaissance mutuelle des identités numériques entre États membres, mais l'adoption est restée faible : seuls 14 % des citoyens disposaient d'une identité numérique reconnue transfrontalièrement. eIDAS 2 ambitionne de créer un portefeuille d'identité numérique européen accessible à tous.",
    summary: "eIDAS 2 modernise le cadre d'identité numérique en créant le portefeuille européen d'identité numérique (EUDIW). Chaque État membre devra fournir gratuitement un portefeuille à ses citoyens permettant de s'identifier en ligne, stocker des attributs vérifiables (diplômes, permis, prescriptions) et signer électroniquement — avec divulgation sélective des données.",
    champ: "États membres (obligation de fournir le portefeuille), services publics nationaux (acceptation obligatoire), très grandes plateformes en ligne au sens du DSA (acceptation obligatoire pour l'authentification), prestataires de services de confiance qualifiés.",
    actors: [
      "États membres (émetteurs du portefeuille EUDIW)",
      "Citoyens et résidents de l'UE (utilisateurs du portefeuille)",
      "Services publics (acceptation obligatoire)",
      "Très grandes plateformes — VLOP (acceptation obligatoire)",
      "Prestataires de services de confiance qualifiés",
    ],
    obligations: [
      "<strong>Mise à disposition du portefeuille (art. 5a)</strong> — chaque État membre doit fournir gratuitement un portefeuille d'identité numérique à ses citoyens et résidents.",
      "<strong>Acceptation obligatoire (art. 5b)</strong> — les services publics et les VLOP doivent accepter le portefeuille EUDIW pour l'authentification.",
      "<strong>Divulgation sélective et pseudonymat</strong> — le portefeuille permet de prouver des attributs sans divulguer l'identité complète.",
      "<strong>Signature électronique qualifiée intégrée</strong> — fonctionnalité de signature accessible gratuitement pour les usages non professionnels.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Renvoyées aux régimes nationaux de supervision des prestataires de services de confiance" },
    ],
    articulations: "eIDAS 2 s'articule avec le DSA (les VLOP doivent accepter le portefeuille), le RGPD (minimisation et contrôle de l'utilisateur), et NIS 2 (les prestataires de services de confiance sont des entités essentielles).",
    timeline: [
      { date: "20 mai 2024", event: "Entrée en vigueur" },
      { date: "Nov. 2024", event: "Publication de l'Architecture Reference Framework (ARF) v1.4" },
      { date: "Mai 2026", event: "Délai pour la mise à disposition du portefeuille EUDIW par les États membres" },
      { date: "2026–2027", event: "Déploiement progressif et certification des portefeuilles" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1183",
    updatedAt: "2025-04-29",
  },
  {
    id: "copyright",
    badge: "Dir. ©",
    cat: "Droits num.",
    name: "Droit d'auteur numérique",
    ref: "Directive (UE) 2019/790",
    type: "Directive",
    status: "transposed",
    statusLabel: "Transposée",
    title: "Directive droit d'auteur",
    fullName: "Directive sur le droit d'auteur et les droits voisins dans le marché unique numérique",
    nature: "directive",
    natureNote: "Directive transposée en France par l'ordonnance n° 2021-580 du 12 mai 2021 et la loi du 24 juin 2020 (droit voisin des éditeurs de presse). C'est la loi française qui s'applique directement.",
    context: "Le droit d'auteur européen n'avait pas été substantiellement réformé depuis 2001. Les plateformes de partage (YouTube, TikTok) sont devenues les principaux canaux de diffusion, les agrégateurs captent la valeur du travail journalistique, et l'exploration de données (TDM) est un outil central pour l'IA.",
    summary: "Cette directive modernise le droit d'auteur autour de trois axes : un droit voisin pour les éditeurs de presse (rémunération par les agrégateurs), la responsabilité des plateformes de partage de contenu (obligation de licence ou de retrait), et des exceptions pour l'exploration de textes et données (TDM) cruciale pour l'entraînement des modèles d'IA.",
    champ: "Plateformes de partage de contenu (YouTube, Instagram, TikTok), éditeurs de presse, agrégateurs d'actualités, organismes de recherche, institutions culturelles. Exclus : encyclopédies en ligne à but non lucratif (Wikipedia), répertoires éducatifs, marketplaces.",
    actors: [
      "Plateformes de partage de contenu (YouTube, Instagram, TikTok)",
      "Éditeurs de presse (bénéficiaires du droit voisin)",
      "Agrégateurs d'actualités (Google News, Apple News)",
      "Auteurs, artistes-interprètes et producteurs",
      "Organismes de recherche (exception TDM)",
    ],
    obligations: [
      "<strong>Droit voisin des éditeurs de presse (art. 15)</strong> — les agrégateurs doivent obtenir une licence et rémunérer les éditeurs pour la réutilisation de publications de presse. Durée : 2 ans.",
      "<strong>Responsabilité des plateformes (art. 17)</strong> — les plateformes sont responsables des contenus protégés non autorisés, sauf si elles ont fait les meilleurs efforts pour obtenir des licences.",
      "<strong>Exception TDM pour la recherche (art. 3)</strong> — les organismes de recherche peuvent reproduire des contenus à des fins scientifiques sans autorisation.",
      "<strong>Exception TDM commerciale (art. 4)</strong> — autorisée sauf si les titulaires ont exercé leur droit d'opt-out. Crucial pour l'entraînement des modèles d'IA.",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "Selon les régimes nationaux de propriété intellectuelle (Code de la propriété intellectuelle en France)" },
    ],
    articulations: "La directive droit d'auteur interagit fortement avec l'AI Act : l'exception TDM est le cadre pour l'entraînement des modèles d'IA. L'AI Act impose aux fournisseurs de GPAI de respecter le droit d'auteur et de publier un résumé des données d'entraînement.",
    timeline: [
      { date: "17 avril 2019", event: "Adoption de la directive" },
      { date: "7 juin 2021", event: "Délai de transposition" },
      { date: "Mai 2021", event: "Transposition française (ordonnance n° 2021-580)" },
      { date: "2022–2026", event: "Contentieux sur le droit voisin (Google, Meta, négociations en cours)" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32019L0790",
    updatedAt: "2025-04-29",
  },
  {
    id: "eprivacy",
    badge: "ePrivacy",
    cat: "Droits num.",
    name: "Vie privée et communications",
    ref: "Directive 2002/58/CE",
    type: "Directive",
    status: "active",
    statusLabel: "En vigueur",
    title: "ePrivacy",
    fullName: "Directive vie privée et communications électroniques",
    nature: "directive",
    natureNote: "La directive ePrivacy est en vigueur depuis 2002, modifiée en 2009. Transposée en France dans le CPCE et la loi Informatique et Libertés. Un projet de règlement ePrivacy est en discussion depuis 2017 mais reste bloqué au Conseil.",
    context: "La directive ePrivacy a été adoptée en 2002 pour compléter la directive de 1995 sur la protection des données avec des règles spécifiques aux communications électroniques. Elle est la lex specialis du RGPD pour ce secteur. Elle est technologiquement datée mais reste le texte applicable.",
    summary: "La directive ePrivacy régit la vie privée dans les communications électroniques : confidentialité des communications, cookies et technologies de traçage (consentement préalable obligatoire sauf cookies strictement nécessaires), données de trafic et de localisation, et communications commerciales non sollicitées (opt-in pour email/SMS marketing).",
    champ: "Fournisseurs de services de communications électroniques (opérateurs télécoms, FAI). L'article 5§3 (cookies) s'applique à tout éditeur de site web ou d'application mobile. La directive ne couvre pas les services OTT comme WhatsApp.",
    actors: [
      "Opérateurs de communications électroniques (Orange, SFR, Bouygues, Free)",
      "Fournisseurs de services en ligne (pour les cookies — tout site web ou application)",
      "Utilisateurs de services de communications électroniques",
      "CNIL (application en France, notamment pour les cookies)",
    ],
    obligations: [
      "<strong>Confidentialité des communications (art. 5)</strong> — interdiction d'intercepter ou surveiller les communications sans consentement.",
      "<strong>Cookies et traceurs (art. 5§3)</strong> — consentement préalable obligatoire. Exceptions : cookies strictement nécessaires à la fourniture du service.",
      "<strong>Données de trafic (art. 6)</strong> — effacement ou anonymisation à la fin de la communication, sauf pour la facturation.",
      "<strong>Communications non sollicitées (art. 13)</strong> — opt-in obligatoire pour email et SMS marketing. Opt-out pour le démarchage téléphonique (Bloctel en France).",
    ],
    sanctions: [
      { amount: "Définies par les États membres", detail: "En France, la CNIL peut prononcer des amendes jusqu'à 2 % du CA mondial pour les manquements relatifs aux cookies." },
    ],
    articulations: "La directive ePrivacy est la lex specialis du RGPD pour les communications électroniques. Le RGPD s'applique pour le traitement ultérieur des données personnelles collectées via cookies. Le règlement ePrivacy, s'il est adopté, remplacera la directive.",
    timeline: [
      { date: "12 juil. 2002", event: "Adoption de la directive" },
      { date: "2009", event: "Modification : ajout du consentement pour les cookies" },
      { date: "2017", event: "Proposition de règlement ePrivacy par la Commission" },
      { date: "2017–présent", event: "Négociations bloquées au Conseil sur le règlement ePrivacy" },
    ],
    link: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32002L0058",
    updatedAt: "2025-04-29",
  },
];

export function getRegulationById(id: string): RegulationData | undefined {
  return regulationsData.find((r) => r.id === id);
}
